packages: []

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry/cli": false
  prisma: true
  sharp: true
  msw: false
  unrs-resolver: false
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  protobufjs: true
  cbor-extract: true
