packages: []

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry/cli": true
  prisma: true
  sharp: true
  supabase: true
  msw: false
  unrs-resolver: false
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
