
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  DictionaryEntry: 'DictionaryEntry',
  DictionarySense: 'DictionarySense',
  DictionaryTranslation: 'DictionaryTranslation',
  DictionaryAlias: 'DictionaryAlias',
  DictionarySourceAudit: 'DictionarySourceAudit',
  Passage: 'Passage',
  StudyChatMessage: 'StudyChatMessage',
  StudioArtifact: 'StudioArtifact',
  Question: 'Question',
  QuizResult: 'QuizResult',
  StudySession: 'StudySession',
  TranslationCache: 'TranslationCache',
  TranslationHistory: 'TranslationHistory',
  FileUploadIntent: 'FileUploadIntent',
  UserProfile: 'UserProfile',
  VocabularyItem: 'VocabularyItem',
  VocabularyOccurrence: 'VocabularyOccurrence',
  VocabularySet: 'VocabularySet',
  VocabularySetItem: 'VocabularySetItem'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "dictionaryEntry" | "dictionarySense" | "dictionaryTranslation" | "dictionaryAlias" | "dictionarySourceAudit" | "passage" | "studyChatMessage" | "studioArtifact" | "question" | "quizResult" | "studySession" | "translationCache" | "translationHistory" | "fileUploadIntent" | "userProfile" | "vocabularyItem" | "vocabularyOccurrence" | "vocabularySet" | "vocabularySetItem"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    DictionaryEntry: {
      payload: Prisma.$DictionaryEntryPayload<ExtArgs>
      fields: Prisma.DictionaryEntryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DictionaryEntryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DictionaryEntryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        findFirst: {
          args: Prisma.DictionaryEntryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DictionaryEntryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        findMany: {
          args: Prisma.DictionaryEntryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>[]
        }
        create: {
          args: Prisma.DictionaryEntryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        createMany: {
          args: Prisma.DictionaryEntryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DictionaryEntryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>[]
        }
        delete: {
          args: Prisma.DictionaryEntryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        update: {
          args: Prisma.DictionaryEntryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        deleteMany: {
          args: Prisma.DictionaryEntryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DictionaryEntryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DictionaryEntryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>[]
        }
        upsert: {
          args: Prisma.DictionaryEntryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryEntryPayload>
        }
        aggregate: {
          args: Prisma.DictionaryEntryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDictionaryEntry>
        }
        groupBy: {
          args: Prisma.DictionaryEntryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryEntryGroupByOutputType>[]
        }
        count: {
          args: Prisma.DictionaryEntryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryEntryCountAggregateOutputType> | number
        }
      }
    }
    DictionarySense: {
      payload: Prisma.$DictionarySensePayload<ExtArgs>
      fields: Prisma.DictionarySenseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DictionarySenseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DictionarySenseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        findFirst: {
          args: Prisma.DictionarySenseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DictionarySenseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        findMany: {
          args: Prisma.DictionarySenseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>[]
        }
        create: {
          args: Prisma.DictionarySenseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        createMany: {
          args: Prisma.DictionarySenseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DictionarySenseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>[]
        }
        delete: {
          args: Prisma.DictionarySenseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        update: {
          args: Prisma.DictionarySenseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        deleteMany: {
          args: Prisma.DictionarySenseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DictionarySenseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DictionarySenseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>[]
        }
        upsert: {
          args: Prisma.DictionarySenseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySensePayload>
        }
        aggregate: {
          args: Prisma.DictionarySenseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDictionarySense>
        }
        groupBy: {
          args: Prisma.DictionarySenseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionarySenseGroupByOutputType>[]
        }
        count: {
          args: Prisma.DictionarySenseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionarySenseCountAggregateOutputType> | number
        }
      }
    }
    DictionaryTranslation: {
      payload: Prisma.$DictionaryTranslationPayload<ExtArgs>
      fields: Prisma.DictionaryTranslationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DictionaryTranslationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DictionaryTranslationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        findFirst: {
          args: Prisma.DictionaryTranslationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DictionaryTranslationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        findMany: {
          args: Prisma.DictionaryTranslationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>[]
        }
        create: {
          args: Prisma.DictionaryTranslationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        createMany: {
          args: Prisma.DictionaryTranslationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DictionaryTranslationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>[]
        }
        delete: {
          args: Prisma.DictionaryTranslationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        update: {
          args: Prisma.DictionaryTranslationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        deleteMany: {
          args: Prisma.DictionaryTranslationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DictionaryTranslationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DictionaryTranslationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>[]
        }
        upsert: {
          args: Prisma.DictionaryTranslationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryTranslationPayload>
        }
        aggregate: {
          args: Prisma.DictionaryTranslationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDictionaryTranslation>
        }
        groupBy: {
          args: Prisma.DictionaryTranslationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryTranslationGroupByOutputType>[]
        }
        count: {
          args: Prisma.DictionaryTranslationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryTranslationCountAggregateOutputType> | number
        }
      }
    }
    DictionaryAlias: {
      payload: Prisma.$DictionaryAliasPayload<ExtArgs>
      fields: Prisma.DictionaryAliasFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DictionaryAliasFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DictionaryAliasFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        findFirst: {
          args: Prisma.DictionaryAliasFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DictionaryAliasFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        findMany: {
          args: Prisma.DictionaryAliasFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>[]
        }
        create: {
          args: Prisma.DictionaryAliasCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        createMany: {
          args: Prisma.DictionaryAliasCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DictionaryAliasCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>[]
        }
        delete: {
          args: Prisma.DictionaryAliasDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        update: {
          args: Prisma.DictionaryAliasUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        deleteMany: {
          args: Prisma.DictionaryAliasDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DictionaryAliasUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DictionaryAliasUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>[]
        }
        upsert: {
          args: Prisma.DictionaryAliasUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionaryAliasPayload>
        }
        aggregate: {
          args: Prisma.DictionaryAliasAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDictionaryAlias>
        }
        groupBy: {
          args: Prisma.DictionaryAliasGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryAliasGroupByOutputType>[]
        }
        count: {
          args: Prisma.DictionaryAliasCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionaryAliasCountAggregateOutputType> | number
        }
      }
    }
    DictionarySourceAudit: {
      payload: Prisma.$DictionarySourceAuditPayload<ExtArgs>
      fields: Prisma.DictionarySourceAuditFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DictionarySourceAuditFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DictionarySourceAuditFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        findFirst: {
          args: Prisma.DictionarySourceAuditFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DictionarySourceAuditFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        findMany: {
          args: Prisma.DictionarySourceAuditFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>[]
        }
        create: {
          args: Prisma.DictionarySourceAuditCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        createMany: {
          args: Prisma.DictionarySourceAuditCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DictionarySourceAuditCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>[]
        }
        delete: {
          args: Prisma.DictionarySourceAuditDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        update: {
          args: Prisma.DictionarySourceAuditUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        deleteMany: {
          args: Prisma.DictionarySourceAuditDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DictionarySourceAuditUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DictionarySourceAuditUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>[]
        }
        upsert: {
          args: Prisma.DictionarySourceAuditUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DictionarySourceAuditPayload>
        }
        aggregate: {
          args: Prisma.DictionarySourceAuditAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDictionarySourceAudit>
        }
        groupBy: {
          args: Prisma.DictionarySourceAuditGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionarySourceAuditGroupByOutputType>[]
        }
        count: {
          args: Prisma.DictionarySourceAuditCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DictionarySourceAuditCountAggregateOutputType> | number
        }
      }
    }
    Passage: {
      payload: Prisma.$PassagePayload<ExtArgs>
      fields: Prisma.PassageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PassageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PassageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        findFirst: {
          args: Prisma.PassageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PassageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        findMany: {
          args: Prisma.PassageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>[]
        }
        create: {
          args: Prisma.PassageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        createMany: {
          args: Prisma.PassageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PassageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>[]
        }
        delete: {
          args: Prisma.PassageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        update: {
          args: Prisma.PassageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        deleteMany: {
          args: Prisma.PassageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PassageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PassageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>[]
        }
        upsert: {
          args: Prisma.PassageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PassagePayload>
        }
        aggregate: {
          args: Prisma.PassageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePassage>
        }
        groupBy: {
          args: Prisma.PassageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PassageGroupByOutputType>[]
        }
        count: {
          args: Prisma.PassageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PassageCountAggregateOutputType> | number
        }
      }
    }
    StudyChatMessage: {
      payload: Prisma.$StudyChatMessagePayload<ExtArgs>
      fields: Prisma.StudyChatMessageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudyChatMessageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudyChatMessageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        findFirst: {
          args: Prisma.StudyChatMessageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudyChatMessageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        findMany: {
          args: Prisma.StudyChatMessageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>[]
        }
        create: {
          args: Prisma.StudyChatMessageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        createMany: {
          args: Prisma.StudyChatMessageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudyChatMessageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>[]
        }
        delete: {
          args: Prisma.StudyChatMessageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        update: {
          args: Prisma.StudyChatMessageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        deleteMany: {
          args: Prisma.StudyChatMessageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudyChatMessageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudyChatMessageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>[]
        }
        upsert: {
          args: Prisma.StudyChatMessageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudyChatMessagePayload>
        }
        aggregate: {
          args: Prisma.StudyChatMessageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudyChatMessage>
        }
        groupBy: {
          args: Prisma.StudyChatMessageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudyChatMessageGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudyChatMessageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudyChatMessageCountAggregateOutputType> | number
        }
      }
    }
    StudioArtifact: {
      payload: Prisma.$StudioArtifactPayload<ExtArgs>
      fields: Prisma.StudioArtifactFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudioArtifactFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudioArtifactFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        findFirst: {
          args: Prisma.StudioArtifactFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudioArtifactFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        findMany: {
          args: Prisma.StudioArtifactFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>[]
        }
        create: {
          args: Prisma.StudioArtifactCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        createMany: {
          args: Prisma.StudioArtifactCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudioArtifactCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>[]
        }
        delete: {
          args: Prisma.StudioArtifactDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        update: {
          args: Prisma.StudioArtifactUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        deleteMany: {
          args: Prisma.StudioArtifactDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudioArtifactUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudioArtifactUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>[]
        }
        upsert: {
          args: Prisma.StudioArtifactUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudioArtifactPayload>
        }
        aggregate: {
          args: Prisma.StudioArtifactAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudioArtifact>
        }
        groupBy: {
          args: Prisma.StudioArtifactGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudioArtifactGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudioArtifactCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudioArtifactCountAggregateOutputType> | number
        }
      }
    }
    Question: {
      payload: Prisma.$QuestionPayload<ExtArgs>
      fields: Prisma.QuestionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.QuestionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.QuestionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        findFirst: {
          args: Prisma.QuestionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.QuestionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        findMany: {
          args: Prisma.QuestionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>[]
        }
        create: {
          args: Prisma.QuestionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        createMany: {
          args: Prisma.QuestionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.QuestionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>[]
        }
        delete: {
          args: Prisma.QuestionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        update: {
          args: Prisma.QuestionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        deleteMany: {
          args: Prisma.QuestionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.QuestionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.QuestionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>[]
        }
        upsert: {
          args: Prisma.QuestionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuestionPayload>
        }
        aggregate: {
          args: Prisma.QuestionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQuestion>
        }
        groupBy: {
          args: Prisma.QuestionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QuestionGroupByOutputType>[]
        }
        count: {
          args: Prisma.QuestionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QuestionCountAggregateOutputType> | number
        }
      }
    }
    QuizResult: {
      payload: Prisma.$QuizResultPayload<ExtArgs>
      fields: Prisma.QuizResultFieldRefs
      operations: {
        findUnique: {
          args: Prisma.QuizResultFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.QuizResultFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        findFirst: {
          args: Prisma.QuizResultFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.QuizResultFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        findMany: {
          args: Prisma.QuizResultFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>[]
        }
        create: {
          args: Prisma.QuizResultCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        createMany: {
          args: Prisma.QuizResultCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.QuizResultCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>[]
        }
        delete: {
          args: Prisma.QuizResultDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        update: {
          args: Prisma.QuizResultUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        deleteMany: {
          args: Prisma.QuizResultDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.QuizResultUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.QuizResultUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>[]
        }
        upsert: {
          args: Prisma.QuizResultUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QuizResultPayload>
        }
        aggregate: {
          args: Prisma.QuizResultAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQuizResult>
        }
        groupBy: {
          args: Prisma.QuizResultGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QuizResultGroupByOutputType>[]
        }
        count: {
          args: Prisma.QuizResultCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QuizResultCountAggregateOutputType> | number
        }
      }
    }
    StudySession: {
      payload: Prisma.$StudySessionPayload<ExtArgs>
      fields: Prisma.StudySessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudySessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudySessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        findFirst: {
          args: Prisma.StudySessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudySessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        findMany: {
          args: Prisma.StudySessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>[]
        }
        create: {
          args: Prisma.StudySessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        createMany: {
          args: Prisma.StudySessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudySessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>[]
        }
        delete: {
          args: Prisma.StudySessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        update: {
          args: Prisma.StudySessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        deleteMany: {
          args: Prisma.StudySessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudySessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudySessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>[]
        }
        upsert: {
          args: Prisma.StudySessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudySessionPayload>
        }
        aggregate: {
          args: Prisma.StudySessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudySession>
        }
        groupBy: {
          args: Prisma.StudySessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudySessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudySessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudySessionCountAggregateOutputType> | number
        }
      }
    }
    TranslationCache: {
      payload: Prisma.$TranslationCachePayload<ExtArgs>
      fields: Prisma.TranslationCacheFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TranslationCacheFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TranslationCacheFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        findFirst: {
          args: Prisma.TranslationCacheFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TranslationCacheFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        findMany: {
          args: Prisma.TranslationCacheFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>[]
        }
        create: {
          args: Prisma.TranslationCacheCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        createMany: {
          args: Prisma.TranslationCacheCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TranslationCacheCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>[]
        }
        delete: {
          args: Prisma.TranslationCacheDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        update: {
          args: Prisma.TranslationCacheUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        deleteMany: {
          args: Prisma.TranslationCacheDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TranslationCacheUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TranslationCacheUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>[]
        }
        upsert: {
          args: Prisma.TranslationCacheUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationCachePayload>
        }
        aggregate: {
          args: Prisma.TranslationCacheAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTranslationCache>
        }
        groupBy: {
          args: Prisma.TranslationCacheGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TranslationCacheGroupByOutputType>[]
        }
        count: {
          args: Prisma.TranslationCacheCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TranslationCacheCountAggregateOutputType> | number
        }
      }
    }
    TranslationHistory: {
      payload: Prisma.$TranslationHistoryPayload<ExtArgs>
      fields: Prisma.TranslationHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TranslationHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TranslationHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        findFirst: {
          args: Prisma.TranslationHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TranslationHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        findMany: {
          args: Prisma.TranslationHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>[]
        }
        create: {
          args: Prisma.TranslationHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        createMany: {
          args: Prisma.TranslationHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TranslationHistoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>[]
        }
        delete: {
          args: Prisma.TranslationHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        update: {
          args: Prisma.TranslationHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        deleteMany: {
          args: Prisma.TranslationHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TranslationHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TranslationHistoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>[]
        }
        upsert: {
          args: Prisma.TranslationHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TranslationHistoryPayload>
        }
        aggregate: {
          args: Prisma.TranslationHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTranslationHistory>
        }
        groupBy: {
          args: Prisma.TranslationHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TranslationHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.TranslationHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TranslationHistoryCountAggregateOutputType> | number
        }
      }
    }
    FileUploadIntent: {
      payload: Prisma.$FileUploadIntentPayload<ExtArgs>
      fields: Prisma.FileUploadIntentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FileUploadIntentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FileUploadIntentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        findFirst: {
          args: Prisma.FileUploadIntentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FileUploadIntentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        findMany: {
          args: Prisma.FileUploadIntentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>[]
        }
        create: {
          args: Prisma.FileUploadIntentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        createMany: {
          args: Prisma.FileUploadIntentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FileUploadIntentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>[]
        }
        delete: {
          args: Prisma.FileUploadIntentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        update: {
          args: Prisma.FileUploadIntentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        deleteMany: {
          args: Prisma.FileUploadIntentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FileUploadIntentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FileUploadIntentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>[]
        }
        upsert: {
          args: Prisma.FileUploadIntentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileUploadIntentPayload>
        }
        aggregate: {
          args: Prisma.FileUploadIntentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFileUploadIntent>
        }
        groupBy: {
          args: Prisma.FileUploadIntentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileUploadIntentGroupByOutputType>[]
        }
        count: {
          args: Prisma.FileUploadIntentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileUploadIntentCountAggregateOutputType> | number
        }
      }
    }
    UserProfile: {
      payload: Prisma.$UserProfilePayload<ExtArgs>
      fields: Prisma.UserProfileFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserProfileFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserProfileFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        findFirst: {
          args: Prisma.UserProfileFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserProfileFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        findMany: {
          args: Prisma.UserProfileFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>[]
        }
        create: {
          args: Prisma.UserProfileCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        createMany: {
          args: Prisma.UserProfileCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserProfileCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>[]
        }
        delete: {
          args: Prisma.UserProfileDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        update: {
          args: Prisma.UserProfileUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        deleteMany: {
          args: Prisma.UserProfileDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserProfileUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserProfileUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>[]
        }
        upsert: {
          args: Prisma.UserProfileUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserProfilePayload>
        }
        aggregate: {
          args: Prisma.UserProfileAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserProfile>
        }
        groupBy: {
          args: Prisma.UserProfileGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserProfileGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserProfileCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserProfileCountAggregateOutputType> | number
        }
      }
    }
    VocabularyItem: {
      payload: Prisma.$VocabularyItemPayload<ExtArgs>
      fields: Prisma.VocabularyItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VocabularyItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VocabularyItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        findFirst: {
          args: Prisma.VocabularyItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VocabularyItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        findMany: {
          args: Prisma.VocabularyItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>[]
        }
        create: {
          args: Prisma.VocabularyItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        createMany: {
          args: Prisma.VocabularyItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VocabularyItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>[]
        }
        delete: {
          args: Prisma.VocabularyItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        update: {
          args: Prisma.VocabularyItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        deleteMany: {
          args: Prisma.VocabularyItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VocabularyItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VocabularyItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>[]
        }
        upsert: {
          args: Prisma.VocabularyItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyItemPayload>
        }
        aggregate: {
          args: Prisma.VocabularyItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVocabularyItem>
        }
        groupBy: {
          args: Prisma.VocabularyItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularyItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.VocabularyItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularyItemCountAggregateOutputType> | number
        }
      }
    }
    VocabularyOccurrence: {
      payload: Prisma.$VocabularyOccurrencePayload<ExtArgs>
      fields: Prisma.VocabularyOccurrenceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VocabularyOccurrenceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VocabularyOccurrenceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        findFirst: {
          args: Prisma.VocabularyOccurrenceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VocabularyOccurrenceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        findMany: {
          args: Prisma.VocabularyOccurrenceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>[]
        }
        create: {
          args: Prisma.VocabularyOccurrenceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        createMany: {
          args: Prisma.VocabularyOccurrenceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VocabularyOccurrenceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>[]
        }
        delete: {
          args: Prisma.VocabularyOccurrenceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        update: {
          args: Prisma.VocabularyOccurrenceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        deleteMany: {
          args: Prisma.VocabularyOccurrenceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VocabularyOccurrenceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VocabularyOccurrenceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>[]
        }
        upsert: {
          args: Prisma.VocabularyOccurrenceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularyOccurrencePayload>
        }
        aggregate: {
          args: Prisma.VocabularyOccurrenceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVocabularyOccurrence>
        }
        groupBy: {
          args: Prisma.VocabularyOccurrenceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularyOccurrenceGroupByOutputType>[]
        }
        count: {
          args: Prisma.VocabularyOccurrenceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularyOccurrenceCountAggregateOutputType> | number
        }
      }
    }
    VocabularySet: {
      payload: Prisma.$VocabularySetPayload<ExtArgs>
      fields: Prisma.VocabularySetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VocabularySetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VocabularySetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        findFirst: {
          args: Prisma.VocabularySetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VocabularySetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        findMany: {
          args: Prisma.VocabularySetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>[]
        }
        create: {
          args: Prisma.VocabularySetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        createMany: {
          args: Prisma.VocabularySetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VocabularySetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>[]
        }
        delete: {
          args: Prisma.VocabularySetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        update: {
          args: Prisma.VocabularySetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        deleteMany: {
          args: Prisma.VocabularySetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VocabularySetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VocabularySetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>[]
        }
        upsert: {
          args: Prisma.VocabularySetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetPayload>
        }
        aggregate: {
          args: Prisma.VocabularySetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVocabularySet>
        }
        groupBy: {
          args: Prisma.VocabularySetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularySetGroupByOutputType>[]
        }
        count: {
          args: Prisma.VocabularySetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularySetCountAggregateOutputType> | number
        }
      }
    }
    VocabularySetItem: {
      payload: Prisma.$VocabularySetItemPayload<ExtArgs>
      fields: Prisma.VocabularySetItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VocabularySetItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VocabularySetItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        findFirst: {
          args: Prisma.VocabularySetItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VocabularySetItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        findMany: {
          args: Prisma.VocabularySetItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>[]
        }
        create: {
          args: Prisma.VocabularySetItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        createMany: {
          args: Prisma.VocabularySetItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VocabularySetItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>[]
        }
        delete: {
          args: Prisma.VocabularySetItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        update: {
          args: Prisma.VocabularySetItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        deleteMany: {
          args: Prisma.VocabularySetItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VocabularySetItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VocabularySetItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>[]
        }
        upsert: {
          args: Prisma.VocabularySetItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VocabularySetItemPayload>
        }
        aggregate: {
          args: Prisma.VocabularySetItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVocabularySetItem>
        }
        groupBy: {
          args: Prisma.VocabularySetItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularySetItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.VocabularySetItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VocabularySetItemCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const DictionaryEntryScalarFieldEnum = {
  id: 'id',
  headword: 'headword',
  normalizedHeadword: 'normalizedHeadword',
  sourceLanguage: 'sourceLanguage',
  frequencyRank: 'frequencyRank',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DictionaryEntryScalarFieldEnum = (typeof DictionaryEntryScalarFieldEnum)[keyof typeof DictionaryEntryScalarFieldEnum]


export const DictionarySenseScalarFieldEnum = {
  id: 'id',
  entryId: 'entryId',
  partOfSpeech: 'partOfSpeech',
  definition: 'definition',
  example: 'example',
  tags: 'tags',
  usageRank: 'usageRank',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DictionarySenseScalarFieldEnum = (typeof DictionarySenseScalarFieldEnum)[keyof typeof DictionarySenseScalarFieldEnum]


export const DictionaryTranslationScalarFieldEnum = {
  id: 'id',
  senseId: 'senseId',
  targetLanguage: 'targetLanguage',
  translation: 'translation',
  isPrimary: 'isPrimary',
  rank: 'rank',
  confidence: 'confidence',
  status: 'status',
  sourceType: 'sourceType',
  sourceName: 'sourceName',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DictionaryTranslationScalarFieldEnum = (typeof DictionaryTranslationScalarFieldEnum)[keyof typeof DictionaryTranslationScalarFieldEnum]


export const DictionaryAliasScalarFieldEnum = {
  id: 'id',
  entryId: 'entryId',
  normalizedAlias: 'normalizedAlias',
  aliasType: 'aliasType'
} as const

export type DictionaryAliasScalarFieldEnum = (typeof DictionaryAliasScalarFieldEnum)[keyof typeof DictionaryAliasScalarFieldEnum]


export const DictionarySourceAuditScalarFieldEnum = {
  id: 'id',
  batchName: 'batchName',
  entityType: 'entityType',
  entityId: 'entityId',
  note: 'note',
  createdAt: 'createdAt'
} as const

export type DictionarySourceAuditScalarFieldEnum = (typeof DictionarySourceAuditScalarFieldEnum)[keyof typeof DictionarySourceAuditScalarFieldEnum]


export const PassageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  content: 'content',
  simplifiedContent: 'simplifiedContent',
  originalLevel: 'originalLevel',
  simplifiedLevel: 'simplifiedLevel',
  wordCount: 'wordCount',
  sourceType: 'sourceType',
  filePath: 'filePath',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PassageScalarFieldEnum = (typeof PassageScalarFieldEnum)[keyof typeof PassageScalarFieldEnum]


export const StudyChatMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  passageId: 'passageId',
  role: 'role',
  content: 'content',
  createdAt: 'createdAt'
} as const

export type StudyChatMessageScalarFieldEnum = (typeof StudyChatMessageScalarFieldEnum)[keyof typeof StudyChatMessageScalarFieldEnum]


export const StudioArtifactScalarFieldEnum = {
  id: 'id',
  passageId: 'passageId',
  userId: 'userId',
  type: 'type',
  title: 'title',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StudioArtifactScalarFieldEnum = (typeof StudioArtifactScalarFieldEnum)[keyof typeof StudioArtifactScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  passageId: 'passageId',
  artifactId: 'artifactId',
  questionText: 'questionText',
  options: 'options',
  correctOption: 'correctOption',
  sourceText: 'sourceText',
  sourceLine: 'sourceLine',
  explanation: 'explanation',
  questionType: 'questionType',
  difficulty: 'difficulty',
  createdAt: 'createdAt'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const QuizResultScalarFieldEnum = {
  id: 'id',
  artifactId: 'artifactId',
  completedAt: 'completedAt',
  correctCount: 'correctCount',
  totalQuestions: 'totalQuestions',
  accuracyRate: 'accuracyRate'
} as const

export type QuizResultScalarFieldEnum = (typeof QuizResultScalarFieldEnum)[keyof typeof QuizResultScalarFieldEnum]


export const StudySessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  startedAt: 'startedAt',
  lastActivityAt: 'lastActivityAt',
  completedAt: 'completedAt'
} as const

export type StudySessionScalarFieldEnum = (typeof StudySessionScalarFieldEnum)[keyof typeof StudySessionScalarFieldEnum]


export const TranslationCacheScalarFieldEnum = {
  id: 'id',
  cacheKey: 'cacheKey',
  userId: 'userId',
  sourceId: 'sourceId',
  selectedText: 'selectedText',
  contextSentence: 'contextSentence',
  sourceLanguage: 'sourceLanguage',
  targetLanguage: 'targetLanguage',
  mode: 'mode',
  provider: 'provider',
  response: 'response',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TranslationCacheScalarFieldEnum = (typeof TranslationCacheScalarFieldEnum)[keyof typeof TranslationCacheScalarFieldEnum]


export const TranslationHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sourceId: 'sourceId',
  selectedText: 'selectedText',
  contextSentence: 'contextSentence',
  sourceLanguage: 'sourceLanguage',
  targetLanguage: 'targetLanguage',
  mode: 'mode',
  provider: 'provider',
  translation: 'translation',
  response: 'response',
  createdAt: 'createdAt'
} as const

export type TranslationHistoryScalarFieldEnum = (typeof TranslationHistoryScalarFieldEnum)[keyof typeof TranslationHistoryScalarFieldEnum]


export const FileUploadIntentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  pathname: 'pathname',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type FileUploadIntentScalarFieldEnum = (typeof FileUploadIntentScalarFieldEnum)[keyof typeof FileUploadIntentScalarFieldEnum]


export const UserProfileScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  avatarUrl: 'avatarUrl',
  bio: 'bio',
  targetLevel: 'targetLevel',
  tier: 'tier',
  stripeCustomerId: 'stripeCustomerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserProfileScalarFieldEnum = (typeof UserProfileScalarFieldEnum)[keyof typeof UserProfileScalarFieldEnum]


export const VocabularyItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  translation: 'translation',
  sourceLanguage: 'sourceLanguage',
  targetLanguage: 'targetLanguage',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  normalizedText: 'normalizedText',
  displayText: 'displayText',
  status: 'status',
  source: 'source',
  savedCount: 'savedCount',
  nextReviewAt: 'nextReviewAt',
  lastReviewedAt: 'lastReviewedAt',
  dictionaryEntryId: 'dictionaryEntryId',
  dictionarySenseId: 'dictionarySenseId'
} as const

export type VocabularyItemScalarFieldEnum = (typeof VocabularyItemScalarFieldEnum)[keyof typeof VocabularyItemScalarFieldEnum]


export const VocabularyOccurrenceScalarFieldEnum = {
  id: 'id',
  vocabularyItemId: 'vocabularyItemId',
  sourceId: 'sourceId',
  selectedText: 'selectedText',
  contextSentence: 'contextSentence',
  createdAt: 'createdAt'
} as const

export type VocabularyOccurrenceScalarFieldEnum = (typeof VocabularyOccurrenceScalarFieldEnum)[keyof typeof VocabularyOccurrenceScalarFieldEnum]


export const VocabularySetScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  type: 'type',
  periodStart: 'periodStart',
  periodEnd: 'periodEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VocabularySetScalarFieldEnum = (typeof VocabularySetScalarFieldEnum)[keyof typeof VocabularySetScalarFieldEnum]


export const VocabularySetItemScalarFieldEnum = {
  id: 'id',
  vocabularySetId: 'vocabularySetId',
  vocabularyItemId: 'vocabularyItemId',
  addedAt: 'addedAt'
} as const

export type VocabularySetItemScalarFieldEnum = (typeof VocabularySetItemScalarFieldEnum)[keyof typeof VocabularySetItemScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'CEFRLevel'
 */
export type EnumCEFRLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CEFRLevel'>
    


/**
 * Reference to a field of type 'CEFRLevel[]'
 */
export type ListEnumCEFRLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CEFRLevel[]'>
    


/**
 * Reference to a field of type 'SourceType'
 */
export type EnumSourceTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SourceType'>
    


/**
 * Reference to a field of type 'SourceType[]'
 */
export type ListEnumSourceTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SourceType[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'QuestionType'
 */
export type EnumQuestionTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QuestionType'>
    


/**
 * Reference to a field of type 'QuestionType[]'
 */
export type ListEnumQuestionTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QuestionType[]'>
    


/**
 * Reference to a field of type 'Tier'
 */
export type EnumTierFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Tier'>
    


/**
 * Reference to a field of type 'Tier[]'
 */
export type ListEnumTierFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Tier[]'>
    


/**
 * Reference to a field of type 'VocabularySetType'
 */
export type EnumVocabularySetTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VocabularySetType'>
    


/**
 * Reference to a field of type 'VocabularySetType[]'
 */
export type ListEnumVocabularySetTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VocabularySetType[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  dictionaryEntry?: Prisma.DictionaryEntryOmit
  dictionarySense?: Prisma.DictionarySenseOmit
  dictionaryTranslation?: Prisma.DictionaryTranslationOmit
  dictionaryAlias?: Prisma.DictionaryAliasOmit
  dictionarySourceAudit?: Prisma.DictionarySourceAuditOmit
  passage?: Prisma.PassageOmit
  studyChatMessage?: Prisma.StudyChatMessageOmit
  studioArtifact?: Prisma.StudioArtifactOmit
  question?: Prisma.QuestionOmit
  quizResult?: Prisma.QuizResultOmit
  studySession?: Prisma.StudySessionOmit
  translationCache?: Prisma.TranslationCacheOmit
  translationHistory?: Prisma.TranslationHistoryOmit
  fileUploadIntent?: Prisma.FileUploadIntentOmit
  userProfile?: Prisma.UserProfileOmit
  vocabularyItem?: Prisma.VocabularyItemOmit
  vocabularyOccurrence?: Prisma.VocabularyOccurrenceOmit
  vocabularySet?: Prisma.VocabularySetOmit
  vocabularySetItem?: Prisma.VocabularySetItemOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

