
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const CEFRLevel = {
  A1: 'A1',
  A2: 'A2',
  B1: 'B1',
  B2: 'B2',
  C1: 'C1',
  C2: 'C2'
} as const

export type CEFRLevel = (typeof CEFRLevel)[keyof typeof CEFRLevel]


export const SourceType = {
  TEXT: 'TEXT',
  PDF: 'PDF'
} as const

export type SourceType = (typeof SourceType)[keyof typeof SourceType]


export const QuestionType = {
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  TRUE_FALSE: 'TRUE_FALSE'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const Tier = {
  FREE: 'FREE',
  PRO: 'PRO'
} as const

export type Tier = (typeof Tier)[keyof typeof Tier]


export const VocabularySetType = {
  MANUAL: 'MANUAL',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY'
} as const

export type VocabularySetType = (typeof VocabularySetType)[keyof typeof VocabularySetType]
