
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DictionaryTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DictionaryTranslation
 * A translation of a sense into a target language, with provenance + ranking.
 * Client: translated meaning(s) under a sense (the primary one highlighted).
 */
export type DictionaryTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$DictionaryTranslationPayload>

export type AggregateDictionaryTranslation = {
  _count: DictionaryTranslationCountAggregateOutputType | null
  _avg: DictionaryTranslationAvgAggregateOutputType | null
  _sum: DictionaryTranslationSumAggregateOutputType | null
  _min: DictionaryTranslationMinAggregateOutputType | null
  _max: DictionaryTranslationMaxAggregateOutputType | null
}

export type DictionaryTranslationAvgAggregateOutputType = {
  rank: number | null
  confidence: number | null
}

export type DictionaryTranslationSumAggregateOutputType = {
  rank: number | null
  confidence: number | null
}

export type DictionaryTranslationMinAggregateOutputType = {
  id: string | null
  senseId: string | null
  targetLanguage: string | null
  translation: string | null
  isPrimary: boolean | null
  rank: number | null
  confidence: number | null
  status: string | null
  sourceType: string | null
  sourceName: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DictionaryTranslationMaxAggregateOutputType = {
  id: string | null
  senseId: string | null
  targetLanguage: string | null
  translation: string | null
  isPrimary: boolean | null
  rank: number | null
  confidence: number | null
  status: string | null
  sourceType: string | null
  sourceName: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DictionaryTranslationCountAggregateOutputType = {
  id: number
  senseId: number
  targetLanguage: number
  translation: number
  isPrimary: number
  rank: number
  confidence: number
  status: number
  sourceType: number
  sourceName: number
  reviewedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DictionaryTranslationAvgAggregateInputType = {
  rank?: true
  confidence?: true
}

export type DictionaryTranslationSumAggregateInputType = {
  rank?: true
  confidence?: true
}

export type DictionaryTranslationMinAggregateInputType = {
  id?: true
  senseId?: true
  targetLanguage?: true
  translation?: true
  isPrimary?: true
  rank?: true
  confidence?: true
  status?: true
  sourceType?: true
  sourceName?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DictionaryTranslationMaxAggregateInputType = {
  id?: true
  senseId?: true
  targetLanguage?: true
  translation?: true
  isPrimary?: true
  rank?: true
  confidence?: true
  status?: true
  sourceType?: true
  sourceName?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DictionaryTranslationCountAggregateInputType = {
  id?: true
  senseId?: true
  targetLanguage?: true
  translation?: true
  isPrimary?: true
  rank?: true
  confidence?: true
  status?: true
  sourceType?: true
  sourceName?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DictionaryTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DictionaryTranslation to aggregate.
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DictionaryTranslations to fetch.
   */
  orderBy?: Prisma.DictionaryTranslationOrderByWithRelationInput | Prisma.DictionaryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DictionaryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DictionaryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DictionaryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DictionaryTranslations
  **/
  _count?: true | DictionaryTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DictionaryTranslationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DictionaryTranslationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DictionaryTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DictionaryTranslationMaxAggregateInputType
}

export type GetDictionaryTranslationAggregateType<T extends DictionaryTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateDictionaryTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDictionaryTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateDictionaryTranslation[P]>
}




export type DictionaryTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DictionaryTranslationWhereInput
  orderBy?: Prisma.DictionaryTranslationOrderByWithAggregationInput | Prisma.DictionaryTranslationOrderByWithAggregationInput[]
  by: Prisma.DictionaryTranslationScalarFieldEnum[] | Prisma.DictionaryTranslationScalarFieldEnum
  having?: Prisma.DictionaryTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DictionaryTranslationCountAggregateInputType | true
  _avg?: DictionaryTranslationAvgAggregateInputType
  _sum?: DictionaryTranslationSumAggregateInputType
  _min?: DictionaryTranslationMinAggregateInputType
  _max?: DictionaryTranslationMaxAggregateInputType
}

export type DictionaryTranslationGroupByOutputType = {
  id: string
  senseId: string
  targetLanguage: string
  translation: string
  isPrimary: boolean
  rank: number
  confidence: number | null
  status: string
  sourceType: string
  sourceName: string | null
  reviewedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DictionaryTranslationCountAggregateOutputType | null
  _avg: DictionaryTranslationAvgAggregateOutputType | null
  _sum: DictionaryTranslationSumAggregateOutputType | null
  _min: DictionaryTranslationMinAggregateOutputType | null
  _max: DictionaryTranslationMaxAggregateOutputType | null
}

export type GetDictionaryTranslationGroupByPayload<T extends DictionaryTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DictionaryTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DictionaryTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DictionaryTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DictionaryTranslationGroupByOutputType[P]>
      }
    >
  >



export type DictionaryTranslationWhereInput = {
  AND?: Prisma.DictionaryTranslationWhereInput | Prisma.DictionaryTranslationWhereInput[]
  OR?: Prisma.DictionaryTranslationWhereInput[]
  NOT?: Prisma.DictionaryTranslationWhereInput | Prisma.DictionaryTranslationWhereInput[]
  id?: Prisma.UuidFilter<"DictionaryTranslation"> | string
  senseId?: Prisma.UuidFilter<"DictionaryTranslation"> | string
  targetLanguage?: Prisma.StringFilter<"DictionaryTranslation"> | string
  translation?: Prisma.StringFilter<"DictionaryTranslation"> | string
  isPrimary?: Prisma.BoolFilter<"DictionaryTranslation"> | boolean
  rank?: Prisma.IntFilter<"DictionaryTranslation"> | number
  confidence?: Prisma.FloatNullableFilter<"DictionaryTranslation"> | number | null
  status?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceType?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceName?: Prisma.StringNullableFilter<"DictionaryTranslation"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"DictionaryTranslation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
  sense?: Prisma.XOR<Prisma.DictionarySenseScalarRelationFilter, Prisma.DictionarySenseWhereInput>
}

export type DictionaryTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  senseId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  sourceName?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sense?: Prisma.DictionarySenseOrderByWithRelationInput
}

export type DictionaryTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DictionaryTranslationWhereInput | Prisma.DictionaryTranslationWhereInput[]
  OR?: Prisma.DictionaryTranslationWhereInput[]
  NOT?: Prisma.DictionaryTranslationWhereInput | Prisma.DictionaryTranslationWhereInput[]
  senseId?: Prisma.UuidFilter<"DictionaryTranslation"> | string
  targetLanguage?: Prisma.StringFilter<"DictionaryTranslation"> | string
  translation?: Prisma.StringFilter<"DictionaryTranslation"> | string
  isPrimary?: Prisma.BoolFilter<"DictionaryTranslation"> | boolean
  rank?: Prisma.IntFilter<"DictionaryTranslation"> | number
  confidence?: Prisma.FloatNullableFilter<"DictionaryTranslation"> | number | null
  status?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceType?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceName?: Prisma.StringNullableFilter<"DictionaryTranslation"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"DictionaryTranslation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
  sense?: Prisma.XOR<Prisma.DictionarySenseScalarRelationFilter, Prisma.DictionarySenseWhereInput>
}, "id">

export type DictionaryTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  senseId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  sourceName?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DictionaryTranslationCountOrderByAggregateInput
  _avg?: Prisma.DictionaryTranslationAvgOrderByAggregateInput
  _max?: Prisma.DictionaryTranslationMaxOrderByAggregateInput
  _min?: Prisma.DictionaryTranslationMinOrderByAggregateInput
  _sum?: Prisma.DictionaryTranslationSumOrderByAggregateInput
}

export type DictionaryTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.DictionaryTranslationScalarWhereWithAggregatesInput | Prisma.DictionaryTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.DictionaryTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DictionaryTranslationScalarWhereWithAggregatesInput | Prisma.DictionaryTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"DictionaryTranslation"> | string
  senseId?: Prisma.UuidWithAggregatesFilter<"DictionaryTranslation"> | string
  targetLanguage?: Prisma.StringWithAggregatesFilter<"DictionaryTranslation"> | string
  translation?: Prisma.StringWithAggregatesFilter<"DictionaryTranslation"> | string
  isPrimary?: Prisma.BoolWithAggregatesFilter<"DictionaryTranslation"> | boolean
  rank?: Prisma.IntWithAggregatesFilter<"DictionaryTranslation"> | number
  confidence?: Prisma.FloatNullableWithAggregatesFilter<"DictionaryTranslation"> | number | null
  status?: Prisma.StringWithAggregatesFilter<"DictionaryTranslation"> | string
  sourceType?: Prisma.StringWithAggregatesFilter<"DictionaryTranslation"> | string
  sourceName?: Prisma.StringNullableWithAggregatesFilter<"DictionaryTranslation"> | string | null
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DictionaryTranslation"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DictionaryTranslation"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DictionaryTranslation"> | Date | string
}

export type DictionaryTranslationCreateInput = {
  id?: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sense: Prisma.DictionarySenseCreateNestedOneWithoutTranslationsInput
}

export type DictionaryTranslationUncheckedCreateInput = {
  id?: string
  senseId: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DictionaryTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sense?: Prisma.DictionarySenseUpdateOneRequiredWithoutTranslationsNestedInput
}

export type DictionaryTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senseId?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DictionaryTranslationCreateManyInput = {
  id?: string
  senseId: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DictionaryTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DictionaryTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senseId?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DictionaryTranslationListRelationFilter = {
  every?: Prisma.DictionaryTranslationWhereInput
  some?: Prisma.DictionaryTranslationWhereInput
  none?: Prisma.DictionaryTranslationWhereInput
}

export type DictionaryTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DictionaryTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senseId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  sourceName?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DictionaryTranslationAvgOrderByAggregateInput = {
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
}

export type DictionaryTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senseId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  sourceName?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DictionaryTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senseId?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  sourceName?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DictionaryTranslationSumOrderByAggregateInput = {
  rank?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
}

export type DictionaryTranslationCreateNestedManyWithoutSenseInput = {
  create?: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput> | Prisma.DictionaryTranslationCreateWithoutSenseInput[] | Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput[]
  connectOrCreate?: Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput | Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput[]
  createMany?: Prisma.DictionaryTranslationCreateManySenseInputEnvelope
  connect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
}

export type DictionaryTranslationUncheckedCreateNestedManyWithoutSenseInput = {
  create?: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput> | Prisma.DictionaryTranslationCreateWithoutSenseInput[] | Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput[]
  connectOrCreate?: Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput | Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput[]
  createMany?: Prisma.DictionaryTranslationCreateManySenseInputEnvelope
  connect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
}

export type DictionaryTranslationUpdateManyWithoutSenseNestedInput = {
  create?: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput> | Prisma.DictionaryTranslationCreateWithoutSenseInput[] | Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput[]
  connectOrCreate?: Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput | Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput[]
  upsert?: Prisma.DictionaryTranslationUpsertWithWhereUniqueWithoutSenseInput | Prisma.DictionaryTranslationUpsertWithWhereUniqueWithoutSenseInput[]
  createMany?: Prisma.DictionaryTranslationCreateManySenseInputEnvelope
  set?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  disconnect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  delete?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  connect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  update?: Prisma.DictionaryTranslationUpdateWithWhereUniqueWithoutSenseInput | Prisma.DictionaryTranslationUpdateWithWhereUniqueWithoutSenseInput[]
  updateMany?: Prisma.DictionaryTranslationUpdateManyWithWhereWithoutSenseInput | Prisma.DictionaryTranslationUpdateManyWithWhereWithoutSenseInput[]
  deleteMany?: Prisma.DictionaryTranslationScalarWhereInput | Prisma.DictionaryTranslationScalarWhereInput[]
}

export type DictionaryTranslationUncheckedUpdateManyWithoutSenseNestedInput = {
  create?: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput> | Prisma.DictionaryTranslationCreateWithoutSenseInput[] | Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput[]
  connectOrCreate?: Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput | Prisma.DictionaryTranslationCreateOrConnectWithoutSenseInput[]
  upsert?: Prisma.DictionaryTranslationUpsertWithWhereUniqueWithoutSenseInput | Prisma.DictionaryTranslationUpsertWithWhereUniqueWithoutSenseInput[]
  createMany?: Prisma.DictionaryTranslationCreateManySenseInputEnvelope
  set?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  disconnect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  delete?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  connect?: Prisma.DictionaryTranslationWhereUniqueInput | Prisma.DictionaryTranslationWhereUniqueInput[]
  update?: Prisma.DictionaryTranslationUpdateWithWhereUniqueWithoutSenseInput | Prisma.DictionaryTranslationUpdateWithWhereUniqueWithoutSenseInput[]
  updateMany?: Prisma.DictionaryTranslationUpdateManyWithWhereWithoutSenseInput | Prisma.DictionaryTranslationUpdateManyWithWhereWithoutSenseInput[]
  deleteMany?: Prisma.DictionaryTranslationScalarWhereInput | Prisma.DictionaryTranslationScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DictionaryTranslationCreateWithoutSenseInput = {
  id?: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DictionaryTranslationUncheckedCreateWithoutSenseInput = {
  id?: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DictionaryTranslationCreateOrConnectWithoutSenseInput = {
  where: Prisma.DictionaryTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput>
}

export type DictionaryTranslationCreateManySenseInputEnvelope = {
  data: Prisma.DictionaryTranslationCreateManySenseInput | Prisma.DictionaryTranslationCreateManySenseInput[]
  skipDuplicates?: boolean
}

export type DictionaryTranslationUpsertWithWhereUniqueWithoutSenseInput = {
  where: Prisma.DictionaryTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.DictionaryTranslationUpdateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedUpdateWithoutSenseInput>
  create: Prisma.XOR<Prisma.DictionaryTranslationCreateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedCreateWithoutSenseInput>
}

export type DictionaryTranslationUpdateWithWhereUniqueWithoutSenseInput = {
  where: Prisma.DictionaryTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.DictionaryTranslationUpdateWithoutSenseInput, Prisma.DictionaryTranslationUncheckedUpdateWithoutSenseInput>
}

export type DictionaryTranslationUpdateManyWithWhereWithoutSenseInput = {
  where: Prisma.DictionaryTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.DictionaryTranslationUpdateManyMutationInput, Prisma.DictionaryTranslationUncheckedUpdateManyWithoutSenseInput>
}

export type DictionaryTranslationScalarWhereInput = {
  AND?: Prisma.DictionaryTranslationScalarWhereInput | Prisma.DictionaryTranslationScalarWhereInput[]
  OR?: Prisma.DictionaryTranslationScalarWhereInput[]
  NOT?: Prisma.DictionaryTranslationScalarWhereInput | Prisma.DictionaryTranslationScalarWhereInput[]
  id?: Prisma.UuidFilter<"DictionaryTranslation"> | string
  senseId?: Prisma.UuidFilter<"DictionaryTranslation"> | string
  targetLanguage?: Prisma.StringFilter<"DictionaryTranslation"> | string
  translation?: Prisma.StringFilter<"DictionaryTranslation"> | string
  isPrimary?: Prisma.BoolFilter<"DictionaryTranslation"> | boolean
  rank?: Prisma.IntFilter<"DictionaryTranslation"> | number
  confidence?: Prisma.FloatNullableFilter<"DictionaryTranslation"> | number | null
  status?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceType?: Prisma.StringFilter<"DictionaryTranslation"> | string
  sourceName?: Prisma.StringNullableFilter<"DictionaryTranslation"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"DictionaryTranslation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DictionaryTranslation"> | Date | string
}

export type DictionaryTranslationCreateManySenseInput = {
  id?: string
  targetLanguage?: string
  translation: string
  isPrimary?: boolean
  rank: number
  confidence?: number | null
  status?: string
  sourceType: string
  sourceName?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DictionaryTranslationUpdateWithoutSenseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DictionaryTranslationUncheckedUpdateWithoutSenseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DictionaryTranslationUncheckedUpdateManyWithoutSenseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  sourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DictionaryTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senseId?: boolean
  targetLanguage?: boolean
  translation?: boolean
  isPrimary?: boolean
  rank?: boolean
  confidence?: boolean
  status?: boolean
  sourceType?: boolean
  sourceName?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dictionaryTranslation"]>

export type DictionaryTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senseId?: boolean
  targetLanguage?: boolean
  translation?: boolean
  isPrimary?: boolean
  rank?: boolean
  confidence?: boolean
  status?: boolean
  sourceType?: boolean
  sourceName?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dictionaryTranslation"]>

export type DictionaryTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senseId?: boolean
  targetLanguage?: boolean
  translation?: boolean
  isPrimary?: boolean
  rank?: boolean
  confidence?: boolean
  status?: boolean
  sourceType?: boolean
  sourceName?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dictionaryTranslation"]>

export type DictionaryTranslationSelectScalar = {
  id?: boolean
  senseId?: boolean
  targetLanguage?: boolean
  translation?: boolean
  isPrimary?: boolean
  rank?: boolean
  confidence?: boolean
  status?: boolean
  sourceType?: boolean
  sourceName?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DictionaryTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "senseId" | "targetLanguage" | "translation" | "isPrimary" | "rank" | "confidence" | "status" | "sourceType" | "sourceName" | "reviewedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["dictionaryTranslation"]>
export type DictionaryTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}
export type DictionaryTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}
export type DictionaryTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sense?: boolean | Prisma.DictionarySenseDefaultArgs<ExtArgs>
}

export type $DictionaryTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DictionaryTranslation"
  objects: {
    sense: Prisma.$DictionarySensePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    senseId: string
    targetLanguage: string
    translation: string
    /**
     * Preferred translation for the sense.
     */
    isPrimary: boolean
    /**
     * Ordering weight among translations (lower = higher priority).
     */
    rank: number
    /**
     * Optional confidence score (0-1) from the source.
     */
    confidence: number | null
    /**
     * Review state: 'draft' by default, promoted after review. Server/admin.
     */
    status: string
    /**
     * Origin pipeline kind (provenance).
     */
    sourceType: string
    sourceName: string | null
    reviewedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dictionaryTranslation"]>
  composites: {}
}

export type DictionaryTranslationGetPayload<S extends boolean | null | undefined | DictionaryTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload, S>

export type DictionaryTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DictionaryTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DictionaryTranslationCountAggregateInputType | true
  }

export interface DictionaryTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DictionaryTranslation'], meta: { name: 'DictionaryTranslation' } }
  /**
   * Find zero or one DictionaryTranslation that matches the filter.
   * @param {DictionaryTranslationFindUniqueArgs} args - Arguments to find a DictionaryTranslation
   * @example
   * // Get one DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DictionaryTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DictionaryTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DictionaryTranslationFindUniqueOrThrowArgs} args - Arguments to find a DictionaryTranslation
   * @example
   * // Get one DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DictionaryTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DictionaryTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationFindFirstArgs} args - Arguments to find a DictionaryTranslation
   * @example
   * // Get one DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DictionaryTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DictionaryTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationFindFirstOrThrowArgs} args - Arguments to find a DictionaryTranslation
   * @example
   * // Get one DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DictionaryTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DictionaryTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DictionaryTranslations
   * const dictionaryTranslations = await prisma.dictionaryTranslation.findMany()
   * 
   * // Get first 10 DictionaryTranslations
   * const dictionaryTranslations = await prisma.dictionaryTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dictionaryTranslationWithIdOnly = await prisma.dictionaryTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DictionaryTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DictionaryTranslation.
   * @param {DictionaryTranslationCreateArgs} args - Arguments to create a DictionaryTranslation.
   * @example
   * // Create one DictionaryTranslation
   * const DictionaryTranslation = await prisma.dictionaryTranslation.create({
   *   data: {
   *     // ... data to create a DictionaryTranslation
   *   }
   * })
   * 
   */
  create<T extends DictionaryTranslationCreateArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DictionaryTranslations.
   * @param {DictionaryTranslationCreateManyArgs} args - Arguments to create many DictionaryTranslations.
   * @example
   * // Create many DictionaryTranslations
   * const dictionaryTranslation = await prisma.dictionaryTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DictionaryTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DictionaryTranslations and returns the data saved in the database.
   * @param {DictionaryTranslationCreateManyAndReturnArgs} args - Arguments to create many DictionaryTranslations.
   * @example
   * // Create many DictionaryTranslations
   * const dictionaryTranslation = await prisma.dictionaryTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DictionaryTranslations and only return the `id`
   * const dictionaryTranslationWithIdOnly = await prisma.dictionaryTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DictionaryTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DictionaryTranslation.
   * @param {DictionaryTranslationDeleteArgs} args - Arguments to delete one DictionaryTranslation.
   * @example
   * // Delete one DictionaryTranslation
   * const DictionaryTranslation = await prisma.dictionaryTranslation.delete({
   *   where: {
   *     // ... filter to delete one DictionaryTranslation
   *   }
   * })
   * 
   */
  delete<T extends DictionaryTranslationDeleteArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DictionaryTranslation.
   * @param {DictionaryTranslationUpdateArgs} args - Arguments to update one DictionaryTranslation.
   * @example
   * // Update one DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DictionaryTranslationUpdateArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DictionaryTranslations.
   * @param {DictionaryTranslationDeleteManyArgs} args - Arguments to filter DictionaryTranslations to delete.
   * @example
   * // Delete a few DictionaryTranslations
   * const { count } = await prisma.dictionaryTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DictionaryTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, DictionaryTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DictionaryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DictionaryTranslations
   * const dictionaryTranslation = await prisma.dictionaryTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DictionaryTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DictionaryTranslations and returns the data updated in the database.
   * @param {DictionaryTranslationUpdateManyAndReturnArgs} args - Arguments to update many DictionaryTranslations.
   * @example
   * // Update many DictionaryTranslations
   * const dictionaryTranslation = await prisma.dictionaryTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DictionaryTranslations and only return the `id`
   * const dictionaryTranslationWithIdOnly = await prisma.dictionaryTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DictionaryTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DictionaryTranslation.
   * @param {DictionaryTranslationUpsertArgs} args - Arguments to update or create a DictionaryTranslation.
   * @example
   * // Update or create a DictionaryTranslation
   * const dictionaryTranslation = await prisma.dictionaryTranslation.upsert({
   *   create: {
   *     // ... data to create a DictionaryTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DictionaryTranslation we want to update
   *   }
   * })
   */
  upsert<T extends DictionaryTranslationUpsertArgs>(args: Prisma.SelectSubset<T, DictionaryTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__DictionaryTranslationClient<runtime.Types.Result.GetResult<Prisma.$DictionaryTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DictionaryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationCountArgs} args - Arguments to filter DictionaryTranslations to count.
   * @example
   * // Count the number of DictionaryTranslations
   * const count = await prisma.dictionaryTranslation.count({
   *   where: {
   *     // ... the filter for the DictionaryTranslations we want to count
   *   }
   * })
  **/
  count<T extends DictionaryTranslationCountArgs>(
    args?: Prisma.Subset<T, DictionaryTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DictionaryTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DictionaryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DictionaryTranslationAggregateArgs>(args: Prisma.Subset<T, DictionaryTranslationAggregateArgs>): Prisma.PrismaPromise<GetDictionaryTranslationAggregateType<T>>

  /**
   * Group by DictionaryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DictionaryTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DictionaryTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DictionaryTranslationGroupByArgs['orderBy'] }
      : { orderBy?: DictionaryTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DictionaryTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDictionaryTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DictionaryTranslation model
 */
readonly fields: DictionaryTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DictionaryTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DictionaryTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sense<T extends Prisma.DictionarySenseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DictionarySenseDefaultArgs<ExtArgs>>): Prisma.Prisma__DictionarySenseClient<runtime.Types.Result.GetResult<Prisma.$DictionarySensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DictionaryTranslation model
 */
export interface DictionaryTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly senseId: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly targetLanguage: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly translation: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly isPrimary: Prisma.FieldRef<"DictionaryTranslation", 'Boolean'>
  readonly rank: Prisma.FieldRef<"DictionaryTranslation", 'Int'>
  readonly confidence: Prisma.FieldRef<"DictionaryTranslation", 'Float'>
  readonly status: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly sourceType: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly sourceName: Prisma.FieldRef<"DictionaryTranslation", 'String'>
  readonly reviewedAt: Prisma.FieldRef<"DictionaryTranslation", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"DictionaryTranslation", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DictionaryTranslation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DictionaryTranslation findUnique
 */
export type DictionaryTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which DictionaryTranslation to fetch.
   */
  where: Prisma.DictionaryTranslationWhereUniqueInput
}

/**
 * DictionaryTranslation findUniqueOrThrow
 */
export type DictionaryTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which DictionaryTranslation to fetch.
   */
  where: Prisma.DictionaryTranslationWhereUniqueInput
}

/**
 * DictionaryTranslation findFirst
 */
export type DictionaryTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which DictionaryTranslation to fetch.
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DictionaryTranslations to fetch.
   */
  orderBy?: Prisma.DictionaryTranslationOrderByWithRelationInput | Prisma.DictionaryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DictionaryTranslations.
   */
  cursor?: Prisma.DictionaryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DictionaryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DictionaryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DictionaryTranslations.
   */
  distinct?: Prisma.DictionaryTranslationScalarFieldEnum | Prisma.DictionaryTranslationScalarFieldEnum[]
}

/**
 * DictionaryTranslation findFirstOrThrow
 */
export type DictionaryTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which DictionaryTranslation to fetch.
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DictionaryTranslations to fetch.
   */
  orderBy?: Prisma.DictionaryTranslationOrderByWithRelationInput | Prisma.DictionaryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DictionaryTranslations.
   */
  cursor?: Prisma.DictionaryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DictionaryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DictionaryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DictionaryTranslations.
   */
  distinct?: Prisma.DictionaryTranslationScalarFieldEnum | Prisma.DictionaryTranslationScalarFieldEnum[]
}

/**
 * DictionaryTranslation findMany
 */
export type DictionaryTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which DictionaryTranslations to fetch.
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DictionaryTranslations to fetch.
   */
  orderBy?: Prisma.DictionaryTranslationOrderByWithRelationInput | Prisma.DictionaryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DictionaryTranslations.
   */
  cursor?: Prisma.DictionaryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DictionaryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DictionaryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DictionaryTranslations.
   */
  distinct?: Prisma.DictionaryTranslationScalarFieldEnum | Prisma.DictionaryTranslationScalarFieldEnum[]
}

/**
 * DictionaryTranslation create
 */
export type DictionaryTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a DictionaryTranslation.
   */
  data: Prisma.XOR<Prisma.DictionaryTranslationCreateInput, Prisma.DictionaryTranslationUncheckedCreateInput>
}

/**
 * DictionaryTranslation createMany
 */
export type DictionaryTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DictionaryTranslations.
   */
  data: Prisma.DictionaryTranslationCreateManyInput | Prisma.DictionaryTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DictionaryTranslation createManyAndReturn
 */
export type DictionaryTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many DictionaryTranslations.
   */
  data: Prisma.DictionaryTranslationCreateManyInput | Prisma.DictionaryTranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DictionaryTranslation update
 */
export type DictionaryTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a DictionaryTranslation.
   */
  data: Prisma.XOR<Prisma.DictionaryTranslationUpdateInput, Prisma.DictionaryTranslationUncheckedUpdateInput>
  /**
   * Choose, which DictionaryTranslation to update.
   */
  where: Prisma.DictionaryTranslationWhereUniqueInput
}

/**
 * DictionaryTranslation updateMany
 */
export type DictionaryTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DictionaryTranslations.
   */
  data: Prisma.XOR<Prisma.DictionaryTranslationUpdateManyMutationInput, Prisma.DictionaryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which DictionaryTranslations to update
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * Limit how many DictionaryTranslations to update.
   */
  limit?: number
}

/**
 * DictionaryTranslation updateManyAndReturn
 */
export type DictionaryTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * The data used to update DictionaryTranslations.
   */
  data: Prisma.XOR<Prisma.DictionaryTranslationUpdateManyMutationInput, Prisma.DictionaryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which DictionaryTranslations to update
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * Limit how many DictionaryTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DictionaryTranslation upsert
 */
export type DictionaryTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the DictionaryTranslation to update in case it exists.
   */
  where: Prisma.DictionaryTranslationWhereUniqueInput
  /**
   * In case the DictionaryTranslation found by the `where` argument doesn't exist, create a new DictionaryTranslation with this data.
   */
  create: Prisma.XOR<Prisma.DictionaryTranslationCreateInput, Prisma.DictionaryTranslationUncheckedCreateInput>
  /**
   * In case the DictionaryTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DictionaryTranslationUpdateInput, Prisma.DictionaryTranslationUncheckedUpdateInput>
}

/**
 * DictionaryTranslation delete
 */
export type DictionaryTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
  /**
   * Filter which DictionaryTranslation to delete.
   */
  where: Prisma.DictionaryTranslationWhereUniqueInput
}

/**
 * DictionaryTranslation deleteMany
 */
export type DictionaryTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DictionaryTranslations to delete
   */
  where?: Prisma.DictionaryTranslationWhereInput
  /**
   * Limit how many DictionaryTranslations to delete.
   */
  limit?: number
}

/**
 * DictionaryTranslation without action
 */
export type DictionaryTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DictionaryTranslation
   */
  select?: Prisma.DictionaryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DictionaryTranslation
   */
  omit?: Prisma.DictionaryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DictionaryTranslationInclude<ExtArgs> | null
}
