
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FileUploadIntent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FileUploadIntent
 * A pending upload authorization: grants temporary, expiring access to a private
 * Blob pathname before the file becomes a Passage. Server-only; consumed/expired
 * after the upload completes. Client: backs the upload flow's signed access.
 */
export type FileUploadIntentModel = runtime.Types.Result.DefaultSelection<Prisma.$FileUploadIntentPayload>

export type AggregateFileUploadIntent = {
  _count: FileUploadIntentCountAggregateOutputType | null
  _min: FileUploadIntentMinAggregateOutputType | null
  _max: FileUploadIntentMaxAggregateOutputType | null
}

export type FileUploadIntentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  pathname: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type FileUploadIntentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  pathname: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type FileUploadIntentCountAggregateOutputType = {
  id: number
  userId: number
  pathname: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type FileUploadIntentMinAggregateInputType = {
  id?: true
  userId?: true
  pathname?: true
  expiresAt?: true
  createdAt?: true
}

export type FileUploadIntentMaxAggregateInputType = {
  id?: true
  userId?: true
  pathname?: true
  expiresAt?: true
  createdAt?: true
}

export type FileUploadIntentCountAggregateInputType = {
  id?: true
  userId?: true
  pathname?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type FileUploadIntentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileUploadIntent to aggregate.
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileUploadIntents to fetch.
   */
  orderBy?: Prisma.FileUploadIntentOrderByWithRelationInput | Prisma.FileUploadIntentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileUploadIntentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileUploadIntents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileUploadIntents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FileUploadIntents
  **/
  _count?: true | FileUploadIntentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileUploadIntentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileUploadIntentMaxAggregateInputType
}

export type GetFileUploadIntentAggregateType<T extends FileUploadIntentAggregateArgs> = {
      [P in keyof T & keyof AggregateFileUploadIntent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileUploadIntent[P]>
    : Prisma.GetScalarType<T[P], AggregateFileUploadIntent[P]>
}




export type FileUploadIntentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileUploadIntentWhereInput
  orderBy?: Prisma.FileUploadIntentOrderByWithAggregationInput | Prisma.FileUploadIntentOrderByWithAggregationInput[]
  by: Prisma.FileUploadIntentScalarFieldEnum[] | Prisma.FileUploadIntentScalarFieldEnum
  having?: Prisma.FileUploadIntentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileUploadIntentCountAggregateInputType | true
  _min?: FileUploadIntentMinAggregateInputType
  _max?: FileUploadIntentMaxAggregateInputType
}

export type FileUploadIntentGroupByOutputType = {
  id: string
  userId: string
  pathname: string
  expiresAt: Date
  createdAt: Date
  _count: FileUploadIntentCountAggregateOutputType | null
  _min: FileUploadIntentMinAggregateOutputType | null
  _max: FileUploadIntentMaxAggregateOutputType | null
}

export type GetFileUploadIntentGroupByPayload<T extends FileUploadIntentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileUploadIntentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileUploadIntentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileUploadIntentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileUploadIntentGroupByOutputType[P]>
      }
    >
  >



export type FileUploadIntentWhereInput = {
  AND?: Prisma.FileUploadIntentWhereInput | Prisma.FileUploadIntentWhereInput[]
  OR?: Prisma.FileUploadIntentWhereInput[]
  NOT?: Prisma.FileUploadIntentWhereInput | Prisma.FileUploadIntentWhereInput[]
  id?: Prisma.UuidFilter<"FileUploadIntent"> | string
  userId?: Prisma.StringFilter<"FileUploadIntent"> | string
  pathname?: Prisma.StringFilter<"FileUploadIntent"> | string
  expiresAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
}

export type FileUploadIntentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  pathname?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserProfileOrderByWithRelationInput
}

export type FileUploadIntentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  pathname?: string
  AND?: Prisma.FileUploadIntentWhereInput | Prisma.FileUploadIntentWhereInput[]
  OR?: Prisma.FileUploadIntentWhereInput[]
  NOT?: Prisma.FileUploadIntentWhereInput | Prisma.FileUploadIntentWhereInput[]
  userId?: Prisma.StringFilter<"FileUploadIntent"> | string
  expiresAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
}, "id" | "pathname">

export type FileUploadIntentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  pathname?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FileUploadIntentCountOrderByAggregateInput
  _max?: Prisma.FileUploadIntentMaxOrderByAggregateInput
  _min?: Prisma.FileUploadIntentMinOrderByAggregateInput
}

export type FileUploadIntentScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileUploadIntentScalarWhereWithAggregatesInput | Prisma.FileUploadIntentScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileUploadIntentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileUploadIntentScalarWhereWithAggregatesInput | Prisma.FileUploadIntentScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"FileUploadIntent"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FileUploadIntent"> | string
  pathname?: Prisma.StringWithAggregatesFilter<"FileUploadIntent"> | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"FileUploadIntent"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FileUploadIntent"> | Date | string
}

export type FileUploadIntentCreateInput = {
  id?: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
  user: Prisma.UserProfileCreateNestedOneWithoutFileUploadIntentsInput
}

export type FileUploadIntentUncheckedCreateInput = {
  id?: string
  userId: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type FileUploadIntentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserProfileUpdateOneRequiredWithoutFileUploadIntentsNestedInput
}

export type FileUploadIntentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUploadIntentCreateManyInput = {
  id?: string
  userId: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type FileUploadIntentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUploadIntentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUploadIntentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  pathname?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FileUploadIntentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  pathname?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FileUploadIntentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  pathname?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FileUploadIntentListRelationFilter = {
  every?: Prisma.FileUploadIntentWhereInput
  some?: Prisma.FileUploadIntentWhereInput
  none?: Prisma.FileUploadIntentWhereInput
}

export type FileUploadIntentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FileUploadIntentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput> | Prisma.FileUploadIntentCreateWithoutUserInput[] | Prisma.FileUploadIntentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FileUploadIntentCreateOrConnectWithoutUserInput | Prisma.FileUploadIntentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FileUploadIntentCreateManyUserInputEnvelope
  connect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
}

export type FileUploadIntentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput> | Prisma.FileUploadIntentCreateWithoutUserInput[] | Prisma.FileUploadIntentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FileUploadIntentCreateOrConnectWithoutUserInput | Prisma.FileUploadIntentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FileUploadIntentCreateManyUserInputEnvelope
  connect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
}

export type FileUploadIntentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput> | Prisma.FileUploadIntentCreateWithoutUserInput[] | Prisma.FileUploadIntentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FileUploadIntentCreateOrConnectWithoutUserInput | Prisma.FileUploadIntentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FileUploadIntentUpsertWithWhereUniqueWithoutUserInput | Prisma.FileUploadIntentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FileUploadIntentCreateManyUserInputEnvelope
  set?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  disconnect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  delete?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  connect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  update?: Prisma.FileUploadIntentUpdateWithWhereUniqueWithoutUserInput | Prisma.FileUploadIntentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FileUploadIntentUpdateManyWithWhereWithoutUserInput | Prisma.FileUploadIntentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FileUploadIntentScalarWhereInput | Prisma.FileUploadIntentScalarWhereInput[]
}

export type FileUploadIntentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput> | Prisma.FileUploadIntentCreateWithoutUserInput[] | Prisma.FileUploadIntentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FileUploadIntentCreateOrConnectWithoutUserInput | Prisma.FileUploadIntentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FileUploadIntentUpsertWithWhereUniqueWithoutUserInput | Prisma.FileUploadIntentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FileUploadIntentCreateManyUserInputEnvelope
  set?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  disconnect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  delete?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  connect?: Prisma.FileUploadIntentWhereUniqueInput | Prisma.FileUploadIntentWhereUniqueInput[]
  update?: Prisma.FileUploadIntentUpdateWithWhereUniqueWithoutUserInput | Prisma.FileUploadIntentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FileUploadIntentUpdateManyWithWhereWithoutUserInput | Prisma.FileUploadIntentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FileUploadIntentScalarWhereInput | Prisma.FileUploadIntentScalarWhereInput[]
}

export type FileUploadIntentCreateWithoutUserInput = {
  id?: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type FileUploadIntentUncheckedCreateWithoutUserInput = {
  id?: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type FileUploadIntentCreateOrConnectWithoutUserInput = {
  where: Prisma.FileUploadIntentWhereUniqueInput
  create: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput>
}

export type FileUploadIntentCreateManyUserInputEnvelope = {
  data: Prisma.FileUploadIntentCreateManyUserInput | Prisma.FileUploadIntentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FileUploadIntentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FileUploadIntentWhereUniqueInput
  update: Prisma.XOR<Prisma.FileUploadIntentUpdateWithoutUserInput, Prisma.FileUploadIntentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FileUploadIntentCreateWithoutUserInput, Prisma.FileUploadIntentUncheckedCreateWithoutUserInput>
}

export type FileUploadIntentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FileUploadIntentWhereUniqueInput
  data: Prisma.XOR<Prisma.FileUploadIntentUpdateWithoutUserInput, Prisma.FileUploadIntentUncheckedUpdateWithoutUserInput>
}

export type FileUploadIntentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FileUploadIntentScalarWhereInput
  data: Prisma.XOR<Prisma.FileUploadIntentUpdateManyMutationInput, Prisma.FileUploadIntentUncheckedUpdateManyWithoutUserInput>
}

export type FileUploadIntentScalarWhereInput = {
  AND?: Prisma.FileUploadIntentScalarWhereInput | Prisma.FileUploadIntentScalarWhereInput[]
  OR?: Prisma.FileUploadIntentScalarWhereInput[]
  NOT?: Prisma.FileUploadIntentScalarWhereInput | Prisma.FileUploadIntentScalarWhereInput[]
  id?: Prisma.UuidFilter<"FileUploadIntent"> | string
  userId?: Prisma.StringFilter<"FileUploadIntent"> | string
  pathname?: Prisma.StringFilter<"FileUploadIntent"> | string
  expiresAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"FileUploadIntent"> | Date | string
}

export type FileUploadIntentCreateManyUserInput = {
  id?: string
  pathname: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type FileUploadIntentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUploadIntentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUploadIntentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathname?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FileUploadIntentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  pathname?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileUploadIntent"]>

export type FileUploadIntentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  pathname?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileUploadIntent"]>

export type FileUploadIntentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  pathname?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileUploadIntent"]>

export type FileUploadIntentSelectScalar = {
  id?: boolean
  userId?: boolean
  pathname?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type FileUploadIntentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "pathname" | "expiresAt" | "createdAt", ExtArgs["result"]["fileUploadIntent"]>
export type FileUploadIntentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}
export type FileUploadIntentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}
export type FileUploadIntentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}

export type $FileUploadIntentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FileUploadIntent"
  objects: {
    user: Prisma.$UserProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    /**
     * Reserved Blob pathname for the upload; unique. Server-only.
     */
    pathname: string
    /**
     * Deadline after which the intent (and its access) is no longer valid.
     */
    expiresAt: Date
    createdAt: Date
  }, ExtArgs["result"]["fileUploadIntent"]>
  composites: {}
}

export type FileUploadIntentGetPayload<S extends boolean | null | undefined | FileUploadIntentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload, S>

export type FileUploadIntentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileUploadIntentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileUploadIntentCountAggregateInputType | true
  }

export interface FileUploadIntentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileUploadIntent'], meta: { name: 'FileUploadIntent' } }
  /**
   * Find zero or one FileUploadIntent that matches the filter.
   * @param {FileUploadIntentFindUniqueArgs} args - Arguments to find a FileUploadIntent
   * @example
   * // Get one FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileUploadIntentFindUniqueArgs>(args: Prisma.SelectSubset<T, FileUploadIntentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FileUploadIntent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileUploadIntentFindUniqueOrThrowArgs} args - Arguments to find a FileUploadIntent
   * @example
   * // Get one FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileUploadIntentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileUploadIntentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileUploadIntent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentFindFirstArgs} args - Arguments to find a FileUploadIntent
   * @example
   * // Get one FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileUploadIntentFindFirstArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileUploadIntent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentFindFirstOrThrowArgs} args - Arguments to find a FileUploadIntent
   * @example
   * // Get one FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileUploadIntentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FileUploadIntents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileUploadIntents
   * const fileUploadIntents = await prisma.fileUploadIntent.findMany()
   * 
   * // Get first 10 FileUploadIntents
   * const fileUploadIntents = await prisma.fileUploadIntent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileUploadIntentWithIdOnly = await prisma.fileUploadIntent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileUploadIntentFindManyArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FileUploadIntent.
   * @param {FileUploadIntentCreateArgs} args - Arguments to create a FileUploadIntent.
   * @example
   * // Create one FileUploadIntent
   * const FileUploadIntent = await prisma.fileUploadIntent.create({
   *   data: {
   *     // ... data to create a FileUploadIntent
   *   }
   * })
   * 
   */
  create<T extends FileUploadIntentCreateArgs>(args: Prisma.SelectSubset<T, FileUploadIntentCreateArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FileUploadIntents.
   * @param {FileUploadIntentCreateManyArgs} args - Arguments to create many FileUploadIntents.
   * @example
   * // Create many FileUploadIntents
   * const fileUploadIntent = await prisma.fileUploadIntent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileUploadIntentCreateManyArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FileUploadIntents and returns the data saved in the database.
   * @param {FileUploadIntentCreateManyAndReturnArgs} args - Arguments to create many FileUploadIntents.
   * @example
   * // Create many FileUploadIntents
   * const fileUploadIntent = await prisma.fileUploadIntent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FileUploadIntents and only return the `id`
   * const fileUploadIntentWithIdOnly = await prisma.fileUploadIntent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FileUploadIntentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FileUploadIntent.
   * @param {FileUploadIntentDeleteArgs} args - Arguments to delete one FileUploadIntent.
   * @example
   * // Delete one FileUploadIntent
   * const FileUploadIntent = await prisma.fileUploadIntent.delete({
   *   where: {
   *     // ... filter to delete one FileUploadIntent
   *   }
   * })
   * 
   */
  delete<T extends FileUploadIntentDeleteArgs>(args: Prisma.SelectSubset<T, FileUploadIntentDeleteArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FileUploadIntent.
   * @param {FileUploadIntentUpdateArgs} args - Arguments to update one FileUploadIntent.
   * @example
   * // Update one FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileUploadIntentUpdateArgs>(args: Prisma.SelectSubset<T, FileUploadIntentUpdateArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FileUploadIntents.
   * @param {FileUploadIntentDeleteManyArgs} args - Arguments to filter FileUploadIntents to delete.
   * @example
   * // Delete a few FileUploadIntents
   * const { count } = await prisma.fileUploadIntent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileUploadIntentDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileUploadIntentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileUploadIntents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileUploadIntents
   * const fileUploadIntent = await prisma.fileUploadIntent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileUploadIntentUpdateManyArgs>(args: Prisma.SelectSubset<T, FileUploadIntentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileUploadIntents and returns the data updated in the database.
   * @param {FileUploadIntentUpdateManyAndReturnArgs} args - Arguments to update many FileUploadIntents.
   * @example
   * // Update many FileUploadIntents
   * const fileUploadIntent = await prisma.fileUploadIntent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FileUploadIntents and only return the `id`
   * const fileUploadIntentWithIdOnly = await prisma.fileUploadIntent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FileUploadIntentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FileUploadIntentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FileUploadIntent.
   * @param {FileUploadIntentUpsertArgs} args - Arguments to update or create a FileUploadIntent.
   * @example
   * // Update or create a FileUploadIntent
   * const fileUploadIntent = await prisma.fileUploadIntent.upsert({
   *   create: {
   *     // ... data to create a FileUploadIntent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileUploadIntent we want to update
   *   }
   * })
   */
  upsert<T extends FileUploadIntentUpsertArgs>(args: Prisma.SelectSubset<T, FileUploadIntentUpsertArgs<ExtArgs>>): Prisma.Prisma__FileUploadIntentClient<runtime.Types.Result.GetResult<Prisma.$FileUploadIntentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FileUploadIntents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentCountArgs} args - Arguments to filter FileUploadIntents to count.
   * @example
   * // Count the number of FileUploadIntents
   * const count = await prisma.fileUploadIntent.count({
   *   where: {
   *     // ... the filter for the FileUploadIntents we want to count
   *   }
   * })
  **/
  count<T extends FileUploadIntentCountArgs>(
    args?: Prisma.Subset<T, FileUploadIntentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileUploadIntentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FileUploadIntent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileUploadIntentAggregateArgs>(args: Prisma.Subset<T, FileUploadIntentAggregateArgs>): Prisma.PrismaPromise<GetFileUploadIntentAggregateType<T>>

  /**
   * Group by FileUploadIntent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUploadIntentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileUploadIntentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileUploadIntentGroupByArgs['orderBy'] }
      : { orderBy?: FileUploadIntentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileUploadIntentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileUploadIntentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FileUploadIntent model
 */
readonly fields: FileUploadIntentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileUploadIntent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileUploadIntentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FileUploadIntent model
 */
export interface FileUploadIntentFieldRefs {
  readonly id: Prisma.FieldRef<"FileUploadIntent", 'String'>
  readonly userId: Prisma.FieldRef<"FileUploadIntent", 'String'>
  readonly pathname: Prisma.FieldRef<"FileUploadIntent", 'String'>
  readonly expiresAt: Prisma.FieldRef<"FileUploadIntent", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"FileUploadIntent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FileUploadIntent findUnique
 */
export type FileUploadIntentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter, which FileUploadIntent to fetch.
   */
  where: Prisma.FileUploadIntentWhereUniqueInput
}

/**
 * FileUploadIntent findUniqueOrThrow
 */
export type FileUploadIntentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter, which FileUploadIntent to fetch.
   */
  where: Prisma.FileUploadIntentWhereUniqueInput
}

/**
 * FileUploadIntent findFirst
 */
export type FileUploadIntentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter, which FileUploadIntent to fetch.
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileUploadIntents to fetch.
   */
  orderBy?: Prisma.FileUploadIntentOrderByWithRelationInput | Prisma.FileUploadIntentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileUploadIntents.
   */
  cursor?: Prisma.FileUploadIntentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileUploadIntents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileUploadIntents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileUploadIntents.
   */
  distinct?: Prisma.FileUploadIntentScalarFieldEnum | Prisma.FileUploadIntentScalarFieldEnum[]
}

/**
 * FileUploadIntent findFirstOrThrow
 */
export type FileUploadIntentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter, which FileUploadIntent to fetch.
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileUploadIntents to fetch.
   */
  orderBy?: Prisma.FileUploadIntentOrderByWithRelationInput | Prisma.FileUploadIntentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileUploadIntents.
   */
  cursor?: Prisma.FileUploadIntentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileUploadIntents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileUploadIntents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileUploadIntents.
   */
  distinct?: Prisma.FileUploadIntentScalarFieldEnum | Prisma.FileUploadIntentScalarFieldEnum[]
}

/**
 * FileUploadIntent findMany
 */
export type FileUploadIntentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter, which FileUploadIntents to fetch.
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileUploadIntents to fetch.
   */
  orderBy?: Prisma.FileUploadIntentOrderByWithRelationInput | Prisma.FileUploadIntentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FileUploadIntents.
   */
  cursor?: Prisma.FileUploadIntentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileUploadIntents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileUploadIntents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileUploadIntents.
   */
  distinct?: Prisma.FileUploadIntentScalarFieldEnum | Prisma.FileUploadIntentScalarFieldEnum[]
}

/**
 * FileUploadIntent create
 */
export type FileUploadIntentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * The data needed to create a FileUploadIntent.
   */
  data: Prisma.XOR<Prisma.FileUploadIntentCreateInput, Prisma.FileUploadIntentUncheckedCreateInput>
}

/**
 * FileUploadIntent createMany
 */
export type FileUploadIntentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FileUploadIntents.
   */
  data: Prisma.FileUploadIntentCreateManyInput | Prisma.FileUploadIntentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileUploadIntent createManyAndReturn
 */
export type FileUploadIntentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * The data used to create many FileUploadIntents.
   */
  data: Prisma.FileUploadIntentCreateManyInput | Prisma.FileUploadIntentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FileUploadIntent update
 */
export type FileUploadIntentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * The data needed to update a FileUploadIntent.
   */
  data: Prisma.XOR<Prisma.FileUploadIntentUpdateInput, Prisma.FileUploadIntentUncheckedUpdateInput>
  /**
   * Choose, which FileUploadIntent to update.
   */
  where: Prisma.FileUploadIntentWhereUniqueInput
}

/**
 * FileUploadIntent updateMany
 */
export type FileUploadIntentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FileUploadIntents.
   */
  data: Prisma.XOR<Prisma.FileUploadIntentUpdateManyMutationInput, Prisma.FileUploadIntentUncheckedUpdateManyInput>
  /**
   * Filter which FileUploadIntents to update
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * Limit how many FileUploadIntents to update.
   */
  limit?: number
}

/**
 * FileUploadIntent updateManyAndReturn
 */
export type FileUploadIntentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * The data used to update FileUploadIntents.
   */
  data: Prisma.XOR<Prisma.FileUploadIntentUpdateManyMutationInput, Prisma.FileUploadIntentUncheckedUpdateManyInput>
  /**
   * Filter which FileUploadIntents to update
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * Limit how many FileUploadIntents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FileUploadIntent upsert
 */
export type FileUploadIntentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * The filter to search for the FileUploadIntent to update in case it exists.
   */
  where: Prisma.FileUploadIntentWhereUniqueInput
  /**
   * In case the FileUploadIntent found by the `where` argument doesn't exist, create a new FileUploadIntent with this data.
   */
  create: Prisma.XOR<Prisma.FileUploadIntentCreateInput, Prisma.FileUploadIntentUncheckedCreateInput>
  /**
   * In case the FileUploadIntent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileUploadIntentUpdateInput, Prisma.FileUploadIntentUncheckedUpdateInput>
}

/**
 * FileUploadIntent delete
 */
export type FileUploadIntentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
  /**
   * Filter which FileUploadIntent to delete.
   */
  where: Prisma.FileUploadIntentWhereUniqueInput
}

/**
 * FileUploadIntent deleteMany
 */
export type FileUploadIntentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileUploadIntents to delete
   */
  where?: Prisma.FileUploadIntentWhereInput
  /**
   * Limit how many FileUploadIntents to delete.
   */
  limit?: number
}

/**
 * FileUploadIntent without action
 */
export type FileUploadIntentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileUploadIntent
   */
  select?: Prisma.FileUploadIntentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileUploadIntent
   */
  omit?: Prisma.FileUploadIntentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileUploadIntentInclude<ExtArgs> | null
}
