
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StudioArtifact` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StudioArtifact
 * A studio output card (a quiz or flashcard set) generated from a passage.
 * Stays generic across types; type-specific rows attach via relations.
 * Client: studio panel cards; status drives the generating/ready/error state.
 */
export type StudioArtifactModel = runtime.Types.Result.DefaultSelection<Prisma.$StudioArtifactPayload>

export type AggregateStudioArtifact = {
  _count: StudioArtifactCountAggregateOutputType | null
  _min: StudioArtifactMinAggregateOutputType | null
  _max: StudioArtifactMaxAggregateOutputType | null
}

export type StudioArtifactMinAggregateOutputType = {
  id: string | null
  passageId: string | null
  userId: string | null
  type: string | null
  title: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StudioArtifactMaxAggregateOutputType = {
  id: string | null
  passageId: string | null
  userId: string | null
  type: string | null
  title: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StudioArtifactCountAggregateOutputType = {
  id: number
  passageId: number
  userId: number
  type: number
  title: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StudioArtifactMinAggregateInputType = {
  id?: true
  passageId?: true
  userId?: true
  type?: true
  title?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type StudioArtifactMaxAggregateInputType = {
  id?: true
  passageId?: true
  userId?: true
  type?: true
  title?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type StudioArtifactCountAggregateInputType = {
  id?: true
  passageId?: true
  userId?: true
  type?: true
  title?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StudioArtifactAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudioArtifact to aggregate.
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudioArtifacts to fetch.
   */
  orderBy?: Prisma.StudioArtifactOrderByWithRelationInput | Prisma.StudioArtifactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudioArtifactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudioArtifacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudioArtifacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StudioArtifacts
  **/
  _count?: true | StudioArtifactCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudioArtifactMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudioArtifactMaxAggregateInputType
}

export type GetStudioArtifactAggregateType<T extends StudioArtifactAggregateArgs> = {
      [P in keyof T & keyof AggregateStudioArtifact]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudioArtifact[P]>
    : Prisma.GetScalarType<T[P], AggregateStudioArtifact[P]>
}




export type StudioArtifactGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudioArtifactWhereInput
  orderBy?: Prisma.StudioArtifactOrderByWithAggregationInput | Prisma.StudioArtifactOrderByWithAggregationInput[]
  by: Prisma.StudioArtifactScalarFieldEnum[] | Prisma.StudioArtifactScalarFieldEnum
  having?: Prisma.StudioArtifactScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudioArtifactCountAggregateInputType | true
  _min?: StudioArtifactMinAggregateInputType
  _max?: StudioArtifactMaxAggregateInputType
}

export type StudioArtifactGroupByOutputType = {
  id: string
  passageId: string
  userId: string
  type: string
  title: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: StudioArtifactCountAggregateOutputType | null
  _min: StudioArtifactMinAggregateOutputType | null
  _max: StudioArtifactMaxAggregateOutputType | null
}

export type GetStudioArtifactGroupByPayload<T extends StudioArtifactGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudioArtifactGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudioArtifactGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudioArtifactGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudioArtifactGroupByOutputType[P]>
      }
    >
  >



export type StudioArtifactWhereInput = {
  AND?: Prisma.StudioArtifactWhereInput | Prisma.StudioArtifactWhereInput[]
  OR?: Prisma.StudioArtifactWhereInput[]
  NOT?: Prisma.StudioArtifactWhereInput | Prisma.StudioArtifactWhereInput[]
  id?: Prisma.UuidFilter<"StudioArtifact"> | string
  passageId?: Prisma.UuidFilter<"StudioArtifact"> | string
  userId?: Prisma.StringFilter<"StudioArtifact"> | string
  type?: Prisma.StringFilter<"StudioArtifact"> | string
  title?: Prisma.StringFilter<"StudioArtifact"> | string
  status?: Prisma.StringFilter<"StudioArtifact"> | string
  createdAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
  passage?: Prisma.XOR<Prisma.PassageScalarRelationFilter, Prisma.PassageWhereInput>
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
  questions?: Prisma.QuestionListRelationFilter
  quizResult?: Prisma.XOR<Prisma.QuizResultNullableScalarRelationFilter, Prisma.QuizResultWhereInput> | null
}

export type StudioArtifactOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  passageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  passage?: Prisma.PassageOrderByWithRelationInput
  user?: Prisma.UserProfileOrderByWithRelationInput
  questions?: Prisma.QuestionOrderByRelationAggregateInput
  quizResult?: Prisma.QuizResultOrderByWithRelationInput
}

export type StudioArtifactWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StudioArtifactWhereInput | Prisma.StudioArtifactWhereInput[]
  OR?: Prisma.StudioArtifactWhereInput[]
  NOT?: Prisma.StudioArtifactWhereInput | Prisma.StudioArtifactWhereInput[]
  passageId?: Prisma.UuidFilter<"StudioArtifact"> | string
  userId?: Prisma.StringFilter<"StudioArtifact"> | string
  type?: Prisma.StringFilter<"StudioArtifact"> | string
  title?: Prisma.StringFilter<"StudioArtifact"> | string
  status?: Prisma.StringFilter<"StudioArtifact"> | string
  createdAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
  passage?: Prisma.XOR<Prisma.PassageScalarRelationFilter, Prisma.PassageWhereInput>
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
  questions?: Prisma.QuestionListRelationFilter
  quizResult?: Prisma.XOR<Prisma.QuizResultNullableScalarRelationFilter, Prisma.QuizResultWhereInput> | null
}, "id">

export type StudioArtifactOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  passageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StudioArtifactCountOrderByAggregateInput
  _max?: Prisma.StudioArtifactMaxOrderByAggregateInput
  _min?: Prisma.StudioArtifactMinOrderByAggregateInput
}

export type StudioArtifactScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudioArtifactScalarWhereWithAggregatesInput | Prisma.StudioArtifactScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudioArtifactScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudioArtifactScalarWhereWithAggregatesInput | Prisma.StudioArtifactScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"StudioArtifact"> | string
  passageId?: Prisma.UuidWithAggregatesFilter<"StudioArtifact"> | string
  userId?: Prisma.StringWithAggregatesFilter<"StudioArtifact"> | string
  type?: Prisma.StringWithAggregatesFilter<"StudioArtifact"> | string
  title?: Prisma.StringWithAggregatesFilter<"StudioArtifact"> | string
  status?: Prisma.StringWithAggregatesFilter<"StudioArtifact"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StudioArtifact"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StudioArtifact"> | Date | string
}

export type StudioArtifactCreateInput = {
  id: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  passage: Prisma.PassageCreateNestedOneWithoutStudioArtifactsInput
  user: Prisma.UserProfileCreateNestedOneWithoutStudioArtifactsInput
  questions?: Prisma.QuestionCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactUncheckedCreateInput = {
  id: string
  passageId: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultUncheckedCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passage?: Prisma.PassageUpdateOneRequiredWithoutStudioArtifactsNestedInput
  user?: Prisma.UserProfileUpdateOneRequiredWithoutStudioArtifactsNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUncheckedUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactCreateManyInput = {
  id: string
  passageId: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StudioArtifactUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StudioArtifactUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StudioArtifactListRelationFilter = {
  every?: Prisma.StudioArtifactWhereInput
  some?: Prisma.StudioArtifactWhereInput
  none?: Prisma.StudioArtifactWhereInput
}

export type StudioArtifactOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudioArtifactCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  passageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudioArtifactMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  passageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudioArtifactMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  passageId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudioArtifactScalarRelationFilter = {
  is?: Prisma.StudioArtifactWhereInput
  isNot?: Prisma.StudioArtifactWhereInput
}

export type StudioArtifactCreateNestedManyWithoutPassageInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput> | Prisma.StudioArtifactCreateWithoutPassageInput[] | Prisma.StudioArtifactUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutPassageInput | Prisma.StudioArtifactCreateOrConnectWithoutPassageInput[]
  createMany?: Prisma.StudioArtifactCreateManyPassageInputEnvelope
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
}

export type StudioArtifactUncheckedCreateNestedManyWithoutPassageInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput> | Prisma.StudioArtifactCreateWithoutPassageInput[] | Prisma.StudioArtifactUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutPassageInput | Prisma.StudioArtifactCreateOrConnectWithoutPassageInput[]
  createMany?: Prisma.StudioArtifactCreateManyPassageInputEnvelope
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
}

export type StudioArtifactUpdateManyWithoutPassageNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput> | Prisma.StudioArtifactCreateWithoutPassageInput[] | Prisma.StudioArtifactUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutPassageInput | Prisma.StudioArtifactCreateOrConnectWithoutPassageInput[]
  upsert?: Prisma.StudioArtifactUpsertWithWhereUniqueWithoutPassageInput | Prisma.StudioArtifactUpsertWithWhereUniqueWithoutPassageInput[]
  createMany?: Prisma.StudioArtifactCreateManyPassageInputEnvelope
  set?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  disconnect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  delete?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  update?: Prisma.StudioArtifactUpdateWithWhereUniqueWithoutPassageInput | Prisma.StudioArtifactUpdateWithWhereUniqueWithoutPassageInput[]
  updateMany?: Prisma.StudioArtifactUpdateManyWithWhereWithoutPassageInput | Prisma.StudioArtifactUpdateManyWithWhereWithoutPassageInput[]
  deleteMany?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
}

export type StudioArtifactUncheckedUpdateManyWithoutPassageNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput> | Prisma.StudioArtifactCreateWithoutPassageInput[] | Prisma.StudioArtifactUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutPassageInput | Prisma.StudioArtifactCreateOrConnectWithoutPassageInput[]
  upsert?: Prisma.StudioArtifactUpsertWithWhereUniqueWithoutPassageInput | Prisma.StudioArtifactUpsertWithWhereUniqueWithoutPassageInput[]
  createMany?: Prisma.StudioArtifactCreateManyPassageInputEnvelope
  set?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  disconnect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  delete?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  update?: Prisma.StudioArtifactUpdateWithWhereUniqueWithoutPassageInput | Prisma.StudioArtifactUpdateWithWhereUniqueWithoutPassageInput[]
  updateMany?: Prisma.StudioArtifactUpdateManyWithWhereWithoutPassageInput | Prisma.StudioArtifactUpdateManyWithWhereWithoutPassageInput[]
  deleteMany?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
}

export type StudioArtifactCreateNestedOneWithoutQuestionsInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutQuestionsInput
  connect?: Prisma.StudioArtifactWhereUniqueInput
}

export type StudioArtifactUpdateOneRequiredWithoutQuestionsNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutQuestionsInput
  upsert?: Prisma.StudioArtifactUpsertWithoutQuestionsInput
  connect?: Prisma.StudioArtifactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudioArtifactUpdateToOneWithWhereWithoutQuestionsInput, Prisma.StudioArtifactUpdateWithoutQuestionsInput>, Prisma.StudioArtifactUncheckedUpdateWithoutQuestionsInput>
}

export type StudioArtifactCreateNestedOneWithoutQuizResultInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedCreateWithoutQuizResultInput>
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutQuizResultInput
  connect?: Prisma.StudioArtifactWhereUniqueInput
}

export type StudioArtifactUpdateOneRequiredWithoutQuizResultNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedCreateWithoutQuizResultInput>
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutQuizResultInput
  upsert?: Prisma.StudioArtifactUpsertWithoutQuizResultInput
  connect?: Prisma.StudioArtifactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudioArtifactUpdateToOneWithWhereWithoutQuizResultInput, Prisma.StudioArtifactUpdateWithoutQuizResultInput>, Prisma.StudioArtifactUncheckedUpdateWithoutQuizResultInput>
}

export type StudioArtifactCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput> | Prisma.StudioArtifactCreateWithoutUserInput[] | Prisma.StudioArtifactUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutUserInput | Prisma.StudioArtifactCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StudioArtifactCreateManyUserInputEnvelope
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
}

export type StudioArtifactUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput> | Prisma.StudioArtifactCreateWithoutUserInput[] | Prisma.StudioArtifactUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutUserInput | Prisma.StudioArtifactCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StudioArtifactCreateManyUserInputEnvelope
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
}

export type StudioArtifactUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput> | Prisma.StudioArtifactCreateWithoutUserInput[] | Prisma.StudioArtifactUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutUserInput | Prisma.StudioArtifactCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StudioArtifactUpsertWithWhereUniqueWithoutUserInput | Prisma.StudioArtifactUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StudioArtifactCreateManyUserInputEnvelope
  set?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  disconnect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  delete?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  update?: Prisma.StudioArtifactUpdateWithWhereUniqueWithoutUserInput | Prisma.StudioArtifactUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StudioArtifactUpdateManyWithWhereWithoutUserInput | Prisma.StudioArtifactUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
}

export type StudioArtifactUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput> | Prisma.StudioArtifactCreateWithoutUserInput[] | Prisma.StudioArtifactUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudioArtifactCreateOrConnectWithoutUserInput | Prisma.StudioArtifactCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StudioArtifactUpsertWithWhereUniqueWithoutUserInput | Prisma.StudioArtifactUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StudioArtifactCreateManyUserInputEnvelope
  set?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  disconnect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  delete?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  connect?: Prisma.StudioArtifactWhereUniqueInput | Prisma.StudioArtifactWhereUniqueInput[]
  update?: Prisma.StudioArtifactUpdateWithWhereUniqueWithoutUserInput | Prisma.StudioArtifactUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StudioArtifactUpdateManyWithWhereWithoutUserInput | Prisma.StudioArtifactUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
}

export type StudioArtifactCreateWithoutPassageInput = {
  id: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserProfileCreateNestedOneWithoutStudioArtifactsInput
  questions?: Prisma.QuestionCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactUncheckedCreateWithoutPassageInput = {
  id: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultUncheckedCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactCreateOrConnectWithoutPassageInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput>
}

export type StudioArtifactCreateManyPassageInputEnvelope = {
  data: Prisma.StudioArtifactCreateManyPassageInput | Prisma.StudioArtifactCreateManyPassageInput[]
  skipDuplicates?: boolean
}

export type StudioArtifactUpsertWithWhereUniqueWithoutPassageInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  update: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutPassageInput, Prisma.StudioArtifactUncheckedUpdateWithoutPassageInput>
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutPassageInput, Prisma.StudioArtifactUncheckedCreateWithoutPassageInput>
}

export type StudioArtifactUpdateWithWhereUniqueWithoutPassageInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutPassageInput, Prisma.StudioArtifactUncheckedUpdateWithoutPassageInput>
}

export type StudioArtifactUpdateManyWithWhereWithoutPassageInput = {
  where: Prisma.StudioArtifactScalarWhereInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateManyMutationInput, Prisma.StudioArtifactUncheckedUpdateManyWithoutPassageInput>
}

export type StudioArtifactScalarWhereInput = {
  AND?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
  OR?: Prisma.StudioArtifactScalarWhereInput[]
  NOT?: Prisma.StudioArtifactScalarWhereInput | Prisma.StudioArtifactScalarWhereInput[]
  id?: Prisma.UuidFilter<"StudioArtifact"> | string
  passageId?: Prisma.UuidFilter<"StudioArtifact"> | string
  userId?: Prisma.StringFilter<"StudioArtifact"> | string
  type?: Prisma.StringFilter<"StudioArtifact"> | string
  title?: Prisma.StringFilter<"StudioArtifact"> | string
  status?: Prisma.StringFilter<"StudioArtifact"> | string
  createdAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StudioArtifact"> | Date | string
}

export type StudioArtifactCreateWithoutQuestionsInput = {
  id: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  passage: Prisma.PassageCreateNestedOneWithoutStudioArtifactsInput
  user: Prisma.UserProfileCreateNestedOneWithoutStudioArtifactsInput
  quizResult?: Prisma.QuizResultCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactUncheckedCreateWithoutQuestionsInput = {
  id: string
  passageId: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quizResult?: Prisma.QuizResultUncheckedCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactCreateOrConnectWithoutQuestionsInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedCreateWithoutQuestionsInput>
}

export type StudioArtifactUpsertWithoutQuestionsInput = {
  update: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedUpdateWithoutQuestionsInput>
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedCreateWithoutQuestionsInput>
  where?: Prisma.StudioArtifactWhereInput
}

export type StudioArtifactUpdateToOneWithWhereWithoutQuestionsInput = {
  where?: Prisma.StudioArtifactWhereInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutQuestionsInput, Prisma.StudioArtifactUncheckedUpdateWithoutQuestionsInput>
}

export type StudioArtifactUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passage?: Prisma.PassageUpdateOneRequiredWithoutStudioArtifactsNestedInput
  user?: Prisma.UserProfileUpdateOneRequiredWithoutStudioArtifactsNestedInput
  quizResult?: Prisma.QuizResultUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quizResult?: Prisma.QuizResultUncheckedUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactCreateWithoutQuizResultInput = {
  id: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  passage: Prisma.PassageCreateNestedOneWithoutStudioArtifactsInput
  user: Prisma.UserProfileCreateNestedOneWithoutStudioArtifactsInput
  questions?: Prisma.QuestionCreateNestedManyWithoutArtifactInput
}

export type StudioArtifactUncheckedCreateWithoutQuizResultInput = {
  id: string
  passageId: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutArtifactInput
}

export type StudioArtifactCreateOrConnectWithoutQuizResultInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedCreateWithoutQuizResultInput>
}

export type StudioArtifactUpsertWithoutQuizResultInput = {
  update: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedUpdateWithoutQuizResultInput>
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedCreateWithoutQuizResultInput>
  where?: Prisma.StudioArtifactWhereInput
}

export type StudioArtifactUpdateToOneWithWhereWithoutQuizResultInput = {
  where?: Prisma.StudioArtifactWhereInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutQuizResultInput, Prisma.StudioArtifactUncheckedUpdateWithoutQuizResultInput>
}

export type StudioArtifactUpdateWithoutQuizResultInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passage?: Prisma.PassageUpdateOneRequiredWithoutStudioArtifactsNestedInput
  user?: Prisma.UserProfileUpdateOneRequiredWithoutStudioArtifactsNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateWithoutQuizResultInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutArtifactNestedInput
}

export type StudioArtifactCreateWithoutUserInput = {
  id: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  passage: Prisma.PassageCreateNestedOneWithoutStudioArtifactsInput
  questions?: Prisma.QuestionCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactUncheckedCreateWithoutUserInput = {
  id: string
  passageId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutArtifactInput
  quizResult?: Prisma.QuizResultUncheckedCreateNestedOneWithoutArtifactInput
}

export type StudioArtifactCreateOrConnectWithoutUserInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput>
}

export type StudioArtifactCreateManyUserInputEnvelope = {
  data: Prisma.StudioArtifactCreateManyUserInput | Prisma.StudioArtifactCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StudioArtifactUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  update: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutUserInput, Prisma.StudioArtifactUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StudioArtifactCreateWithoutUserInput, Prisma.StudioArtifactUncheckedCreateWithoutUserInput>
}

export type StudioArtifactUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StudioArtifactWhereUniqueInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateWithoutUserInput, Prisma.StudioArtifactUncheckedUpdateWithoutUserInput>
}

export type StudioArtifactUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StudioArtifactScalarWhereInput
  data: Prisma.XOR<Prisma.StudioArtifactUpdateManyMutationInput, Prisma.StudioArtifactUncheckedUpdateManyWithoutUserInput>
}

export type StudioArtifactCreateManyPassageInput = {
  id: string
  userId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StudioArtifactUpdateWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserProfileUpdateOneRequiredWithoutStudioArtifactsNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUncheckedUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateManyWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StudioArtifactCreateManyUserInput = {
  id: string
  passageId: string
  type: string
  title: string
  status: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StudioArtifactUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passage?: Prisma.PassageUpdateOneRequiredWithoutStudioArtifactsNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutArtifactNestedInput
  quizResult?: Prisma.QuizResultUncheckedUpdateOneWithoutArtifactNestedInput
}

export type StudioArtifactUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passageId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type StudioArtifactCountOutputType
 */

export type StudioArtifactCountOutputType = {
  questions: number
}

export type StudioArtifactCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  questions?: boolean | StudioArtifactCountOutputTypeCountQuestionsArgs
}

/**
 * StudioArtifactCountOutputType without action
 */
export type StudioArtifactCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifactCountOutputType
   */
  select?: Prisma.StudioArtifactCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StudioArtifactCountOutputType without action
 */
export type StudioArtifactCountOutputTypeCountQuestionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionWhereInput
}


export type StudioArtifactSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  passageId?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  questions?: boolean | Prisma.StudioArtifact$questionsArgs<ExtArgs>
  quizResult?: boolean | Prisma.StudioArtifact$quizResultArgs<ExtArgs>
  _count?: boolean | Prisma.StudioArtifactCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studioArtifact"]>

export type StudioArtifactSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  passageId?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studioArtifact"]>

export type StudioArtifactSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  passageId?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studioArtifact"]>

export type StudioArtifactSelectScalar = {
  id?: boolean
  passageId?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StudioArtifactOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "passageId" | "userId" | "type" | "title" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["studioArtifact"]>
export type StudioArtifactInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  questions?: boolean | Prisma.StudioArtifact$questionsArgs<ExtArgs>
  quizResult?: boolean | Prisma.StudioArtifact$quizResultArgs<ExtArgs>
  _count?: boolean | Prisma.StudioArtifactCountOutputTypeDefaultArgs<ExtArgs>
}
export type StudioArtifactIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}
export type StudioArtifactIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
}

export type $StudioArtifactPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StudioArtifact"
  objects: {
    passage: Prisma.$PassagePayload<ExtArgs>
    user: Prisma.$UserProfilePayload<ExtArgs>
    questions: Prisma.$QuestionPayload<ExtArgs>[]
    quizResult: Prisma.$QuizResultPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * UUID supplied by the client at creation (optimistic card) — NOT db-generated.
     */
    id: string
    passageId: string
    userId: string
    /**
     * Artifact kind: 'quiz' | 'flashcard'.
     */
    type: string
    title: string
    /**
     * Generation state: 'generating' | 'done' | 'failed'.
     */
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["studioArtifact"]>
  composites: {}
}

export type StudioArtifactGetPayload<S extends boolean | null | undefined | StudioArtifactDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload, S>

export type StudioArtifactCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudioArtifactFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudioArtifactCountAggregateInputType | true
  }

export interface StudioArtifactDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StudioArtifact'], meta: { name: 'StudioArtifact' } }
  /**
   * Find zero or one StudioArtifact that matches the filter.
   * @param {StudioArtifactFindUniqueArgs} args - Arguments to find a StudioArtifact
   * @example
   * // Get one StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudioArtifactFindUniqueArgs>(args: Prisma.SelectSubset<T, StudioArtifactFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StudioArtifact that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudioArtifactFindUniqueOrThrowArgs} args - Arguments to find a StudioArtifact
   * @example
   * // Get one StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudioArtifactFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudioArtifactFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudioArtifact that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactFindFirstArgs} args - Arguments to find a StudioArtifact
   * @example
   * // Get one StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudioArtifactFindFirstArgs>(args?: Prisma.SelectSubset<T, StudioArtifactFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudioArtifact that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactFindFirstOrThrowArgs} args - Arguments to find a StudioArtifact
   * @example
   * // Get one StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudioArtifactFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudioArtifactFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StudioArtifacts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StudioArtifacts
   * const studioArtifacts = await prisma.studioArtifact.findMany()
   * 
   * // Get first 10 StudioArtifacts
   * const studioArtifacts = await prisma.studioArtifact.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studioArtifactWithIdOnly = await prisma.studioArtifact.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudioArtifactFindManyArgs>(args?: Prisma.SelectSubset<T, StudioArtifactFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StudioArtifact.
   * @param {StudioArtifactCreateArgs} args - Arguments to create a StudioArtifact.
   * @example
   * // Create one StudioArtifact
   * const StudioArtifact = await prisma.studioArtifact.create({
   *   data: {
   *     // ... data to create a StudioArtifact
   *   }
   * })
   * 
   */
  create<T extends StudioArtifactCreateArgs>(args: Prisma.SelectSubset<T, StudioArtifactCreateArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StudioArtifacts.
   * @param {StudioArtifactCreateManyArgs} args - Arguments to create many StudioArtifacts.
   * @example
   * // Create many StudioArtifacts
   * const studioArtifact = await prisma.studioArtifact.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudioArtifactCreateManyArgs>(args?: Prisma.SelectSubset<T, StudioArtifactCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StudioArtifacts and returns the data saved in the database.
   * @param {StudioArtifactCreateManyAndReturnArgs} args - Arguments to create many StudioArtifacts.
   * @example
   * // Create many StudioArtifacts
   * const studioArtifact = await prisma.studioArtifact.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StudioArtifacts and only return the `id`
   * const studioArtifactWithIdOnly = await prisma.studioArtifact.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudioArtifactCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudioArtifactCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StudioArtifact.
   * @param {StudioArtifactDeleteArgs} args - Arguments to delete one StudioArtifact.
   * @example
   * // Delete one StudioArtifact
   * const StudioArtifact = await prisma.studioArtifact.delete({
   *   where: {
   *     // ... filter to delete one StudioArtifact
   *   }
   * })
   * 
   */
  delete<T extends StudioArtifactDeleteArgs>(args: Prisma.SelectSubset<T, StudioArtifactDeleteArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StudioArtifact.
   * @param {StudioArtifactUpdateArgs} args - Arguments to update one StudioArtifact.
   * @example
   * // Update one StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudioArtifactUpdateArgs>(args: Prisma.SelectSubset<T, StudioArtifactUpdateArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StudioArtifacts.
   * @param {StudioArtifactDeleteManyArgs} args - Arguments to filter StudioArtifacts to delete.
   * @example
   * // Delete a few StudioArtifacts
   * const { count } = await prisma.studioArtifact.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudioArtifactDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudioArtifactDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudioArtifacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StudioArtifacts
   * const studioArtifact = await prisma.studioArtifact.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudioArtifactUpdateManyArgs>(args: Prisma.SelectSubset<T, StudioArtifactUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudioArtifacts and returns the data updated in the database.
   * @param {StudioArtifactUpdateManyAndReturnArgs} args - Arguments to update many StudioArtifacts.
   * @example
   * // Update many StudioArtifacts
   * const studioArtifact = await prisma.studioArtifact.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StudioArtifacts and only return the `id`
   * const studioArtifactWithIdOnly = await prisma.studioArtifact.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudioArtifactUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudioArtifactUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StudioArtifact.
   * @param {StudioArtifactUpsertArgs} args - Arguments to update or create a StudioArtifact.
   * @example
   * // Update or create a StudioArtifact
   * const studioArtifact = await prisma.studioArtifact.upsert({
   *   create: {
   *     // ... data to create a StudioArtifact
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StudioArtifact we want to update
   *   }
   * })
   */
  upsert<T extends StudioArtifactUpsertArgs>(args: Prisma.SelectSubset<T, StudioArtifactUpsertArgs<ExtArgs>>): Prisma.Prisma__StudioArtifactClient<runtime.Types.Result.GetResult<Prisma.$StudioArtifactPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StudioArtifacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactCountArgs} args - Arguments to filter StudioArtifacts to count.
   * @example
   * // Count the number of StudioArtifacts
   * const count = await prisma.studioArtifact.count({
   *   where: {
   *     // ... the filter for the StudioArtifacts we want to count
   *   }
   * })
  **/
  count<T extends StudioArtifactCountArgs>(
    args?: Prisma.Subset<T, StudioArtifactCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudioArtifactCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StudioArtifact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudioArtifactAggregateArgs>(args: Prisma.Subset<T, StudioArtifactAggregateArgs>): Prisma.PrismaPromise<GetStudioArtifactAggregateType<T>>

  /**
   * Group by StudioArtifact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudioArtifactGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudioArtifactGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudioArtifactGroupByArgs['orderBy'] }
      : { orderBy?: StudioArtifactGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudioArtifactGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudioArtifactGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StudioArtifact model
 */
readonly fields: StudioArtifactFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StudioArtifact.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudioArtifactClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  passage<T extends Prisma.PassageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PassageDefaultArgs<ExtArgs>>): Prisma.Prisma__PassageClient<runtime.Types.Result.GetResult<Prisma.$PassagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  questions<T extends Prisma.StudioArtifact$questionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudioArtifact$questionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  quizResult<T extends Prisma.StudioArtifact$quizResultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudioArtifact$quizResultArgs<ExtArgs>>): Prisma.Prisma__QuizResultClient<runtime.Types.Result.GetResult<Prisma.$QuizResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StudioArtifact model
 */
export interface StudioArtifactFieldRefs {
  readonly id: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly passageId: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly userId: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly type: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly title: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly status: Prisma.FieldRef<"StudioArtifact", 'String'>
  readonly createdAt: Prisma.FieldRef<"StudioArtifact", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StudioArtifact", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StudioArtifact findUnique
 */
export type StudioArtifactFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter, which StudioArtifact to fetch.
   */
  where: Prisma.StudioArtifactWhereUniqueInput
}

/**
 * StudioArtifact findUniqueOrThrow
 */
export type StudioArtifactFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter, which StudioArtifact to fetch.
   */
  where: Prisma.StudioArtifactWhereUniqueInput
}

/**
 * StudioArtifact findFirst
 */
export type StudioArtifactFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter, which StudioArtifact to fetch.
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudioArtifacts to fetch.
   */
  orderBy?: Prisma.StudioArtifactOrderByWithRelationInput | Prisma.StudioArtifactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudioArtifacts.
   */
  cursor?: Prisma.StudioArtifactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudioArtifacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudioArtifacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudioArtifacts.
   */
  distinct?: Prisma.StudioArtifactScalarFieldEnum | Prisma.StudioArtifactScalarFieldEnum[]
}

/**
 * StudioArtifact findFirstOrThrow
 */
export type StudioArtifactFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter, which StudioArtifact to fetch.
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudioArtifacts to fetch.
   */
  orderBy?: Prisma.StudioArtifactOrderByWithRelationInput | Prisma.StudioArtifactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudioArtifacts.
   */
  cursor?: Prisma.StudioArtifactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudioArtifacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudioArtifacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudioArtifacts.
   */
  distinct?: Prisma.StudioArtifactScalarFieldEnum | Prisma.StudioArtifactScalarFieldEnum[]
}

/**
 * StudioArtifact findMany
 */
export type StudioArtifactFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter, which StudioArtifacts to fetch.
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudioArtifacts to fetch.
   */
  orderBy?: Prisma.StudioArtifactOrderByWithRelationInput | Prisma.StudioArtifactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StudioArtifacts.
   */
  cursor?: Prisma.StudioArtifactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudioArtifacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudioArtifacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudioArtifacts.
   */
  distinct?: Prisma.StudioArtifactScalarFieldEnum | Prisma.StudioArtifactScalarFieldEnum[]
}

/**
 * StudioArtifact create
 */
export type StudioArtifactCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * The data needed to create a StudioArtifact.
   */
  data: Prisma.XOR<Prisma.StudioArtifactCreateInput, Prisma.StudioArtifactUncheckedCreateInput>
}

/**
 * StudioArtifact createMany
 */
export type StudioArtifactCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StudioArtifacts.
   */
  data: Prisma.StudioArtifactCreateManyInput | Prisma.StudioArtifactCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudioArtifact createManyAndReturn
 */
export type StudioArtifactCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * The data used to create many StudioArtifacts.
   */
  data: Prisma.StudioArtifactCreateManyInput | Prisma.StudioArtifactCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StudioArtifact update
 */
export type StudioArtifactUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * The data needed to update a StudioArtifact.
   */
  data: Prisma.XOR<Prisma.StudioArtifactUpdateInput, Prisma.StudioArtifactUncheckedUpdateInput>
  /**
   * Choose, which StudioArtifact to update.
   */
  where: Prisma.StudioArtifactWhereUniqueInput
}

/**
 * StudioArtifact updateMany
 */
export type StudioArtifactUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StudioArtifacts.
   */
  data: Prisma.XOR<Prisma.StudioArtifactUpdateManyMutationInput, Prisma.StudioArtifactUncheckedUpdateManyInput>
  /**
   * Filter which StudioArtifacts to update
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * Limit how many StudioArtifacts to update.
   */
  limit?: number
}

/**
 * StudioArtifact updateManyAndReturn
 */
export type StudioArtifactUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * The data used to update StudioArtifacts.
   */
  data: Prisma.XOR<Prisma.StudioArtifactUpdateManyMutationInput, Prisma.StudioArtifactUncheckedUpdateManyInput>
  /**
   * Filter which StudioArtifacts to update
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * Limit how many StudioArtifacts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StudioArtifact upsert
 */
export type StudioArtifactUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * The filter to search for the StudioArtifact to update in case it exists.
   */
  where: Prisma.StudioArtifactWhereUniqueInput
  /**
   * In case the StudioArtifact found by the `where` argument doesn't exist, create a new StudioArtifact with this data.
   */
  create: Prisma.XOR<Prisma.StudioArtifactCreateInput, Prisma.StudioArtifactUncheckedCreateInput>
  /**
   * In case the StudioArtifact was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudioArtifactUpdateInput, Prisma.StudioArtifactUncheckedUpdateInput>
}

/**
 * StudioArtifact delete
 */
export type StudioArtifactDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
  /**
   * Filter which StudioArtifact to delete.
   */
  where: Prisma.StudioArtifactWhereUniqueInput
}

/**
 * StudioArtifact deleteMany
 */
export type StudioArtifactDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudioArtifacts to delete
   */
  where?: Prisma.StudioArtifactWhereInput
  /**
   * Limit how many StudioArtifacts to delete.
   */
  limit?: number
}

/**
 * StudioArtifact.questions
 */
export type StudioArtifact$questionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Question
   */
  select?: Prisma.QuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Question
   */
  omit?: Prisma.QuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionInclude<ExtArgs> | null
  where?: Prisma.QuestionWhereInput
  orderBy?: Prisma.QuestionOrderByWithRelationInput | Prisma.QuestionOrderByWithRelationInput[]
  cursor?: Prisma.QuestionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuestionScalarFieldEnum | Prisma.QuestionScalarFieldEnum[]
}

/**
 * StudioArtifact.quizResult
 */
export type StudioArtifact$quizResultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResult
   */
  select?: Prisma.QuizResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResult
   */
  omit?: Prisma.QuizResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResultInclude<ExtArgs> | null
  where?: Prisma.QuizResultWhereInput
}

/**
 * StudioArtifact without action
 */
export type StudioArtifactDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudioArtifact
   */
  select?: Prisma.StudioArtifactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudioArtifact
   */
  omit?: Prisma.StudioArtifactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudioArtifactInclude<ExtArgs> | null
}
