
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TranslationHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TranslationHistory
 * Append-only log of translations the learner performed. Client: translation
 * history list; unlike the cache, every lookup is recorded.
 */
export type TranslationHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$TranslationHistoryPayload>

export type AggregateTranslationHistory = {
  _count: TranslationHistoryCountAggregateOutputType | null
  _min: TranslationHistoryMinAggregateOutputType | null
  _max: TranslationHistoryMaxAggregateOutputType | null
}

export type TranslationHistoryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  sourceId: string | null
  selectedText: string | null
  contextSentence: string | null
  sourceLanguage: string | null
  targetLanguage: string | null
  mode: string | null
  provider: string | null
  translation: string | null
  createdAt: Date | null
}

export type TranslationHistoryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  sourceId: string | null
  selectedText: string | null
  contextSentence: string | null
  sourceLanguage: string | null
  targetLanguage: string | null
  mode: string | null
  provider: string | null
  translation: string | null
  createdAt: Date | null
}

export type TranslationHistoryCountAggregateOutputType = {
  id: number
  userId: number
  sourceId: number
  selectedText: number
  contextSentence: number
  sourceLanguage: number
  targetLanguage: number
  mode: number
  provider: number
  translation: number
  response: number
  createdAt: number
  _all: number
}


export type TranslationHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  sourceId?: true
  selectedText?: true
  contextSentence?: true
  sourceLanguage?: true
  targetLanguage?: true
  mode?: true
  provider?: true
  translation?: true
  createdAt?: true
}

export type TranslationHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  sourceId?: true
  selectedText?: true
  contextSentence?: true
  sourceLanguage?: true
  targetLanguage?: true
  mode?: true
  provider?: true
  translation?: true
  createdAt?: true
}

export type TranslationHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  sourceId?: true
  selectedText?: true
  contextSentence?: true
  sourceLanguage?: true
  targetLanguage?: true
  mode?: true
  provider?: true
  translation?: true
  response?: true
  createdAt?: true
  _all?: true
}

export type TranslationHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationHistory to aggregate.
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationHistories to fetch.
   */
  orderBy?: Prisma.TranslationHistoryOrderByWithRelationInput | Prisma.TranslationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TranslationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TranslationHistories
  **/
  _count?: true | TranslationHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TranslationHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TranslationHistoryMaxAggregateInputType
}

export type GetTranslationHistoryAggregateType<T extends TranslationHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateTranslationHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTranslationHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateTranslationHistory[P]>
}




export type TranslationHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TranslationHistoryWhereInput
  orderBy?: Prisma.TranslationHistoryOrderByWithAggregationInput | Prisma.TranslationHistoryOrderByWithAggregationInput[]
  by: Prisma.TranslationHistoryScalarFieldEnum[] | Prisma.TranslationHistoryScalarFieldEnum
  having?: Prisma.TranslationHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TranslationHistoryCountAggregateInputType | true
  _min?: TranslationHistoryMinAggregateInputType
  _max?: TranslationHistoryMaxAggregateInputType
}

export type TranslationHistoryGroupByOutputType = {
  id: string
  userId: string
  sourceId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: runtime.JsonValue
  createdAt: Date
  _count: TranslationHistoryCountAggregateOutputType | null
  _min: TranslationHistoryMinAggregateOutputType | null
  _max: TranslationHistoryMaxAggregateOutputType | null
}

export type GetTranslationHistoryGroupByPayload<T extends TranslationHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TranslationHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TranslationHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TranslationHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TranslationHistoryGroupByOutputType[P]>
      }
    >
  >



export type TranslationHistoryWhereInput = {
  AND?: Prisma.TranslationHistoryWhereInput | Prisma.TranslationHistoryWhereInput[]
  OR?: Prisma.TranslationHistoryWhereInput[]
  NOT?: Prisma.TranslationHistoryWhereInput | Prisma.TranslationHistoryWhereInput[]
  id?: Prisma.UuidFilter<"TranslationHistory"> | string
  userId?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceId?: Prisma.UuidFilter<"TranslationHistory"> | string
  selectedText?: Prisma.StringFilter<"TranslationHistory"> | string
  contextSentence?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  targetLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  mode?: Prisma.StringFilter<"TranslationHistory"> | string
  provider?: Prisma.StringFilter<"TranslationHistory"> | string
  translation?: Prisma.StringFilter<"TranslationHistory"> | string
  response?: Prisma.JsonFilter<"TranslationHistory">
  createdAt?: Prisma.DateTimeFilter<"TranslationHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
  passage?: Prisma.XOR<Prisma.PassageScalarRelationFilter, Prisma.PassageWhereInput>
}

export type TranslationHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  selectedText?: Prisma.SortOrder
  contextSentence?: Prisma.SortOrder
  sourceLanguage?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserProfileOrderByWithRelationInput
  passage?: Prisma.PassageOrderByWithRelationInput
}

export type TranslationHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TranslationHistoryWhereInput | Prisma.TranslationHistoryWhereInput[]
  OR?: Prisma.TranslationHistoryWhereInput[]
  NOT?: Prisma.TranslationHistoryWhereInput | Prisma.TranslationHistoryWhereInput[]
  userId?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceId?: Prisma.UuidFilter<"TranslationHistory"> | string
  selectedText?: Prisma.StringFilter<"TranslationHistory"> | string
  contextSentence?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  targetLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  mode?: Prisma.StringFilter<"TranslationHistory"> | string
  provider?: Prisma.StringFilter<"TranslationHistory"> | string
  translation?: Prisma.StringFilter<"TranslationHistory"> | string
  response?: Prisma.JsonFilter<"TranslationHistory">
  createdAt?: Prisma.DateTimeFilter<"TranslationHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserProfileScalarRelationFilter, Prisma.UserProfileWhereInput>
  passage?: Prisma.XOR<Prisma.PassageScalarRelationFilter, Prisma.PassageWhereInput>
}, "id">

export type TranslationHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  selectedText?: Prisma.SortOrder
  contextSentence?: Prisma.SortOrder
  sourceLanguage?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TranslationHistoryCountOrderByAggregateInput
  _max?: Prisma.TranslationHistoryMaxOrderByAggregateInput
  _min?: Prisma.TranslationHistoryMinOrderByAggregateInput
}

export type TranslationHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.TranslationHistoryScalarWhereWithAggregatesInput | Prisma.TranslationHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.TranslationHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TranslationHistoryScalarWhereWithAggregatesInput | Prisma.TranslationHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"TranslationHistory"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  sourceId?: Prisma.UuidWithAggregatesFilter<"TranslationHistory"> | string
  selectedText?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  contextSentence?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  sourceLanguage?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  targetLanguage?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  mode?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  provider?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  translation?: Prisma.StringWithAggregatesFilter<"TranslationHistory"> | string
  response?: Prisma.JsonWithAggregatesFilter<"TranslationHistory">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TranslationHistory"> | Date | string
}

export type TranslationHistoryCreateInput = {
  id?: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user: Prisma.UserProfileCreateNestedOneWithoutTranslationHistoriesInput
  passage: Prisma.PassageCreateNestedOneWithoutTranslationHistoriesInput
}

export type TranslationHistoryUncheckedCreateInput = {
  id?: string
  userId: string
  sourceId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserProfileUpdateOneRequiredWithoutTranslationHistoriesNestedInput
  passage?: Prisma.PassageUpdateOneRequiredWithoutTranslationHistoriesNestedInput
}

export type TranslationHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryCreateManyInput = {
  id?: string
  userId: string
  sourceId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryListRelationFilter = {
  every?: Prisma.TranslationHistoryWhereInput
  some?: Prisma.TranslationHistoryWhereInput
  none?: Prisma.TranslationHistoryWhereInput
}

export type TranslationHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TranslationHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  selectedText?: Prisma.SortOrder
  contextSentence?: Prisma.SortOrder
  sourceLanguage?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TranslationHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  selectedText?: Prisma.SortOrder
  contextSentence?: Prisma.SortOrder
  sourceLanguage?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TranslationHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  selectedText?: Prisma.SortOrder
  contextSentence?: Prisma.SortOrder
  sourceLanguage?: Prisma.SortOrder
  targetLanguage?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  translation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TranslationHistoryCreateNestedManyWithoutPassageInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput> | Prisma.TranslationHistoryCreateWithoutPassageInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput | Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput[]
  createMany?: Prisma.TranslationHistoryCreateManyPassageInputEnvelope
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
}

export type TranslationHistoryUncheckedCreateNestedManyWithoutPassageInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput> | Prisma.TranslationHistoryCreateWithoutPassageInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput | Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput[]
  createMany?: Prisma.TranslationHistoryCreateManyPassageInputEnvelope
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
}

export type TranslationHistoryUpdateManyWithoutPassageNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput> | Prisma.TranslationHistoryCreateWithoutPassageInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput | Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput[]
  upsert?: Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutPassageInput | Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutPassageInput[]
  createMany?: Prisma.TranslationHistoryCreateManyPassageInputEnvelope
  set?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  disconnect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  delete?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  update?: Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutPassageInput | Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutPassageInput[]
  updateMany?: Prisma.TranslationHistoryUpdateManyWithWhereWithoutPassageInput | Prisma.TranslationHistoryUpdateManyWithWhereWithoutPassageInput[]
  deleteMany?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
}

export type TranslationHistoryUncheckedUpdateManyWithoutPassageNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput> | Prisma.TranslationHistoryCreateWithoutPassageInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput | Prisma.TranslationHistoryCreateOrConnectWithoutPassageInput[]
  upsert?: Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutPassageInput | Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutPassageInput[]
  createMany?: Prisma.TranslationHistoryCreateManyPassageInputEnvelope
  set?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  disconnect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  delete?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  update?: Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutPassageInput | Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutPassageInput[]
  updateMany?: Prisma.TranslationHistoryUpdateManyWithWhereWithoutPassageInput | Prisma.TranslationHistoryUpdateManyWithWhereWithoutPassageInput[]
  deleteMany?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
}

export type TranslationHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput> | Prisma.TranslationHistoryCreateWithoutUserInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutUserInput | Prisma.TranslationHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TranslationHistoryCreateManyUserInputEnvelope
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
}

export type TranslationHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput> | Prisma.TranslationHistoryCreateWithoutUserInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutUserInput | Prisma.TranslationHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TranslationHistoryCreateManyUserInputEnvelope
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
}

export type TranslationHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput> | Prisma.TranslationHistoryCreateWithoutUserInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutUserInput | Prisma.TranslationHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TranslationHistoryCreateManyUserInputEnvelope
  set?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  disconnect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  delete?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  update?: Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TranslationHistoryUpdateManyWithWhereWithoutUserInput | Prisma.TranslationHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
}

export type TranslationHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput> | Prisma.TranslationHistoryCreateWithoutUserInput[] | Prisma.TranslationHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TranslationHistoryCreateOrConnectWithoutUserInput | Prisma.TranslationHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.TranslationHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TranslationHistoryCreateManyUserInputEnvelope
  set?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  disconnect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  delete?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  connect?: Prisma.TranslationHistoryWhereUniqueInput | Prisma.TranslationHistoryWhereUniqueInput[]
  update?: Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.TranslationHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TranslationHistoryUpdateManyWithWhereWithoutUserInput | Prisma.TranslationHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
}

export type TranslationHistoryCreateWithoutPassageInput = {
  id?: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user: Prisma.UserProfileCreateNestedOneWithoutTranslationHistoriesInput
}

export type TranslationHistoryUncheckedCreateWithoutPassageInput = {
  id?: string
  userId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryCreateOrConnectWithoutPassageInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput>
}

export type TranslationHistoryCreateManyPassageInputEnvelope = {
  data: Prisma.TranslationHistoryCreateManyPassageInput | Prisma.TranslationHistoryCreateManyPassageInput[]
  skipDuplicates?: boolean
}

export type TranslationHistoryUpsertWithWhereUniqueWithoutPassageInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.TranslationHistoryUpdateWithoutPassageInput, Prisma.TranslationHistoryUncheckedUpdateWithoutPassageInput>
  create: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutPassageInput, Prisma.TranslationHistoryUncheckedCreateWithoutPassageInput>
}

export type TranslationHistoryUpdateWithWhereUniqueWithoutPassageInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateWithoutPassageInput, Prisma.TranslationHistoryUncheckedUpdateWithoutPassageInput>
}

export type TranslationHistoryUpdateManyWithWhereWithoutPassageInput = {
  where: Prisma.TranslationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateManyMutationInput, Prisma.TranslationHistoryUncheckedUpdateManyWithoutPassageInput>
}

export type TranslationHistoryScalarWhereInput = {
  AND?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
  OR?: Prisma.TranslationHistoryScalarWhereInput[]
  NOT?: Prisma.TranslationHistoryScalarWhereInput | Prisma.TranslationHistoryScalarWhereInput[]
  id?: Prisma.UuidFilter<"TranslationHistory"> | string
  userId?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceId?: Prisma.UuidFilter<"TranslationHistory"> | string
  selectedText?: Prisma.StringFilter<"TranslationHistory"> | string
  contextSentence?: Prisma.StringFilter<"TranslationHistory"> | string
  sourceLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  targetLanguage?: Prisma.StringFilter<"TranslationHistory"> | string
  mode?: Prisma.StringFilter<"TranslationHistory"> | string
  provider?: Prisma.StringFilter<"TranslationHistory"> | string
  translation?: Prisma.StringFilter<"TranslationHistory"> | string
  response?: Prisma.JsonFilter<"TranslationHistory">
  createdAt?: Prisma.DateTimeFilter<"TranslationHistory"> | Date | string
}

export type TranslationHistoryCreateWithoutUserInput = {
  id?: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  passage: Prisma.PassageCreateNestedOneWithoutTranslationHistoriesInput
}

export type TranslationHistoryUncheckedCreateWithoutUserInput = {
  id?: string
  sourceId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput>
}

export type TranslationHistoryCreateManyUserInputEnvelope = {
  data: Prisma.TranslationHistoryCreateManyUserInput | Prisma.TranslationHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TranslationHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.TranslationHistoryUpdateWithoutUserInput, Prisma.TranslationHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TranslationHistoryCreateWithoutUserInput, Prisma.TranslationHistoryUncheckedCreateWithoutUserInput>
}

export type TranslationHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TranslationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateWithoutUserInput, Prisma.TranslationHistoryUncheckedUpdateWithoutUserInput>
}

export type TranslationHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TranslationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateManyMutationInput, Prisma.TranslationHistoryUncheckedUpdateManyWithoutUserInput>
}

export type TranslationHistoryCreateManyPassageInput = {
  id?: string
  userId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryUpdateWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserProfileUpdateOneRequiredWithoutTranslationHistoriesNestedInput
}

export type TranslationHistoryUncheckedUpdateWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryUncheckedUpdateManyWithoutPassageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryCreateManyUserInput = {
  id?: string
  sourceId: string
  selectedText: string
  contextSentence: string
  sourceLanguage: string
  targetLanguage: string
  mode: string
  provider: string
  translation: string
  response: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TranslationHistoryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passage?: Prisma.PassageUpdateOneRequiredWithoutTranslationHistoriesNestedInput
}

export type TranslationHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedText?: Prisma.StringFieldUpdateOperationsInput | string
  contextSentence?: Prisma.StringFieldUpdateOperationsInput | string
  sourceLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  targetLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  translation?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TranslationHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  sourceId?: boolean
  selectedText?: boolean
  contextSentence?: boolean
  sourceLanguage?: boolean
  targetLanguage?: boolean
  mode?: boolean
  provider?: boolean
  translation?: boolean
  response?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationHistory"]>

export type TranslationHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  sourceId?: boolean
  selectedText?: boolean
  contextSentence?: boolean
  sourceLanguage?: boolean
  targetLanguage?: boolean
  mode?: boolean
  provider?: boolean
  translation?: boolean
  response?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationHistory"]>

export type TranslationHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  sourceId?: boolean
  selectedText?: boolean
  contextSentence?: boolean
  sourceLanguage?: boolean
  targetLanguage?: boolean
  mode?: boolean
  provider?: boolean
  translation?: boolean
  response?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationHistory"]>

export type TranslationHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  sourceId?: boolean
  selectedText?: boolean
  contextSentence?: boolean
  sourceLanguage?: boolean
  targetLanguage?: boolean
  mode?: boolean
  provider?: boolean
  translation?: boolean
  response?: boolean
  createdAt?: boolean
}

export type TranslationHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "sourceId" | "selectedText" | "contextSentence" | "sourceLanguage" | "targetLanguage" | "mode" | "provider" | "translation" | "response" | "createdAt", ExtArgs["result"]["translationHistory"]>
export type TranslationHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}
export type TranslationHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}
export type TranslationHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>
  passage?: boolean | Prisma.PassageDefaultArgs<ExtArgs>
}

export type $TranslationHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TranslationHistory"
  objects: {
    user: Prisma.$UserProfilePayload<ExtArgs>
    passage: Prisma.$PassagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    /**
     * Passage the selection came from. FK -> passages.id.
     */
    sourceId: string
    selectedText: string
    /**
     * Surrounding sentence captured at lookup time.
     */
    contextSentence: string
    sourceLanguage: string
    targetLanguage: string
    /**
     * Lookup mode (e.g. 'quick') — internal routing value.
     */
    mode: string
    /**
     * Backend that produced the result (see TranslationCache.provider values).
     */
    provider: string
    translation: string
    response: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["translationHistory"]>
  composites: {}
}

export type TranslationHistoryGetPayload<S extends boolean | null | undefined | TranslationHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload, S>

export type TranslationHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TranslationHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TranslationHistoryCountAggregateInputType | true
  }

export interface TranslationHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TranslationHistory'], meta: { name: 'TranslationHistory' } }
  /**
   * Find zero or one TranslationHistory that matches the filter.
   * @param {TranslationHistoryFindUniqueArgs} args - Arguments to find a TranslationHistory
   * @example
   * // Get one TranslationHistory
   * const translationHistory = await prisma.translationHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TranslationHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, TranslationHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TranslationHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TranslationHistoryFindUniqueOrThrowArgs} args - Arguments to find a TranslationHistory
   * @example
   * // Get one TranslationHistory
   * const translationHistory = await prisma.translationHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TranslationHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TranslationHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryFindFirstArgs} args - Arguments to find a TranslationHistory
   * @example
   * // Get one TranslationHistory
   * const translationHistory = await prisma.translationHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TranslationHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryFindFirstOrThrowArgs} args - Arguments to find a TranslationHistory
   * @example
   * // Get one TranslationHistory
   * const translationHistory = await prisma.translationHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TranslationHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TranslationHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TranslationHistories
   * const translationHistories = await prisma.translationHistory.findMany()
   * 
   * // Get first 10 TranslationHistories
   * const translationHistories = await prisma.translationHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const translationHistoryWithIdOnly = await prisma.translationHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TranslationHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TranslationHistory.
   * @param {TranslationHistoryCreateArgs} args - Arguments to create a TranslationHistory.
   * @example
   * // Create one TranslationHistory
   * const TranslationHistory = await prisma.translationHistory.create({
   *   data: {
   *     // ... data to create a TranslationHistory
   *   }
   * })
   * 
   */
  create<T extends TranslationHistoryCreateArgs>(args: Prisma.SelectSubset<T, TranslationHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TranslationHistories.
   * @param {TranslationHistoryCreateManyArgs} args - Arguments to create many TranslationHistories.
   * @example
   * // Create many TranslationHistories
   * const translationHistory = await prisma.translationHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TranslationHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TranslationHistories and returns the data saved in the database.
   * @param {TranslationHistoryCreateManyAndReturnArgs} args - Arguments to create many TranslationHistories.
   * @example
   * // Create many TranslationHistories
   * const translationHistory = await prisma.translationHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TranslationHistories and only return the `id`
   * const translationHistoryWithIdOnly = await prisma.translationHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TranslationHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TranslationHistory.
   * @param {TranslationHistoryDeleteArgs} args - Arguments to delete one TranslationHistory.
   * @example
   * // Delete one TranslationHistory
   * const TranslationHistory = await prisma.translationHistory.delete({
   *   where: {
   *     // ... filter to delete one TranslationHistory
   *   }
   * })
   * 
   */
  delete<T extends TranslationHistoryDeleteArgs>(args: Prisma.SelectSubset<T, TranslationHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TranslationHistory.
   * @param {TranslationHistoryUpdateArgs} args - Arguments to update one TranslationHistory.
   * @example
   * // Update one TranslationHistory
   * const translationHistory = await prisma.translationHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TranslationHistoryUpdateArgs>(args: Prisma.SelectSubset<T, TranslationHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TranslationHistories.
   * @param {TranslationHistoryDeleteManyArgs} args - Arguments to filter TranslationHistories to delete.
   * @example
   * // Delete a few TranslationHistories
   * const { count } = await prisma.translationHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TranslationHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, TranslationHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TranslationHistories
   * const translationHistory = await prisma.translationHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TranslationHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, TranslationHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationHistories and returns the data updated in the database.
   * @param {TranslationHistoryUpdateManyAndReturnArgs} args - Arguments to update many TranslationHistories.
   * @example
   * // Update many TranslationHistories
   * const translationHistory = await prisma.translationHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TranslationHistories and only return the `id`
   * const translationHistoryWithIdOnly = await prisma.translationHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TranslationHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TranslationHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TranslationHistory.
   * @param {TranslationHistoryUpsertArgs} args - Arguments to update or create a TranslationHistory.
   * @example
   * // Update or create a TranslationHistory
   * const translationHistory = await prisma.translationHistory.upsert({
   *   create: {
   *     // ... data to create a TranslationHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TranslationHistory we want to update
   *   }
   * })
   */
  upsert<T extends TranslationHistoryUpsertArgs>(args: Prisma.SelectSubset<T, TranslationHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__TranslationHistoryClient<runtime.Types.Result.GetResult<Prisma.$TranslationHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TranslationHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryCountArgs} args - Arguments to filter TranslationHistories to count.
   * @example
   * // Count the number of TranslationHistories
   * const count = await prisma.translationHistory.count({
   *   where: {
   *     // ... the filter for the TranslationHistories we want to count
   *   }
   * })
  **/
  count<T extends TranslationHistoryCountArgs>(
    args?: Prisma.Subset<T, TranslationHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TranslationHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TranslationHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TranslationHistoryAggregateArgs>(args: Prisma.Subset<T, TranslationHistoryAggregateArgs>): Prisma.PrismaPromise<GetTranslationHistoryAggregateType<T>>

  /**
   * Group by TranslationHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TranslationHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TranslationHistoryGroupByArgs['orderBy'] }
      : { orderBy?: TranslationHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TranslationHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTranslationHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TranslationHistory model
 */
readonly fields: TranslationHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TranslationHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TranslationHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  passage<T extends Prisma.PassageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PassageDefaultArgs<ExtArgs>>): Prisma.Prisma__PassageClient<runtime.Types.Result.GetResult<Prisma.$PassagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TranslationHistory model
 */
export interface TranslationHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly userId: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly sourceId: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly selectedText: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly contextSentence: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly sourceLanguage: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly targetLanguage: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly mode: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly provider: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly translation: Prisma.FieldRef<"TranslationHistory", 'String'>
  readonly response: Prisma.FieldRef<"TranslationHistory", 'Json'>
  readonly createdAt: Prisma.FieldRef<"TranslationHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TranslationHistory findUnique
 */
export type TranslationHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TranslationHistory to fetch.
   */
  where: Prisma.TranslationHistoryWhereUniqueInput
}

/**
 * TranslationHistory findUniqueOrThrow
 */
export type TranslationHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TranslationHistory to fetch.
   */
  where: Prisma.TranslationHistoryWhereUniqueInput
}

/**
 * TranslationHistory findFirst
 */
export type TranslationHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TranslationHistory to fetch.
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationHistories to fetch.
   */
  orderBy?: Prisma.TranslationHistoryOrderByWithRelationInput | Prisma.TranslationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationHistories.
   */
  cursor?: Prisma.TranslationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationHistories.
   */
  distinct?: Prisma.TranslationHistoryScalarFieldEnum | Prisma.TranslationHistoryScalarFieldEnum[]
}

/**
 * TranslationHistory findFirstOrThrow
 */
export type TranslationHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TranslationHistory to fetch.
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationHistories to fetch.
   */
  orderBy?: Prisma.TranslationHistoryOrderByWithRelationInput | Prisma.TranslationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationHistories.
   */
  cursor?: Prisma.TranslationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationHistories.
   */
  distinct?: Prisma.TranslationHistoryScalarFieldEnum | Prisma.TranslationHistoryScalarFieldEnum[]
}

/**
 * TranslationHistory findMany
 */
export type TranslationHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TranslationHistories to fetch.
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationHistories to fetch.
   */
  orderBy?: Prisma.TranslationHistoryOrderByWithRelationInput | Prisma.TranslationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TranslationHistories.
   */
  cursor?: Prisma.TranslationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationHistories.
   */
  distinct?: Prisma.TranslationHistoryScalarFieldEnum | Prisma.TranslationHistoryScalarFieldEnum[]
}

/**
 * TranslationHistory create
 */
export type TranslationHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a TranslationHistory.
   */
  data: Prisma.XOR<Prisma.TranslationHistoryCreateInput, Prisma.TranslationHistoryUncheckedCreateInput>
}

/**
 * TranslationHistory createMany
 */
export type TranslationHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TranslationHistories.
   */
  data: Prisma.TranslationHistoryCreateManyInput | Prisma.TranslationHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TranslationHistory createManyAndReturn
 */
export type TranslationHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many TranslationHistories.
   */
  data: Prisma.TranslationHistoryCreateManyInput | Prisma.TranslationHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationHistory update
 */
export type TranslationHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a TranslationHistory.
   */
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateInput, Prisma.TranslationHistoryUncheckedUpdateInput>
  /**
   * Choose, which TranslationHistory to update.
   */
  where: Prisma.TranslationHistoryWhereUniqueInput
}

/**
 * TranslationHistory updateMany
 */
export type TranslationHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TranslationHistories.
   */
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateManyMutationInput, Prisma.TranslationHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TranslationHistories to update
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * Limit how many TranslationHistories to update.
   */
  limit?: number
}

/**
 * TranslationHistory updateManyAndReturn
 */
export type TranslationHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * The data used to update TranslationHistories.
   */
  data: Prisma.XOR<Prisma.TranslationHistoryUpdateManyMutationInput, Prisma.TranslationHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TranslationHistories to update
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * Limit how many TranslationHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationHistory upsert
 */
export type TranslationHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the TranslationHistory to update in case it exists.
   */
  where: Prisma.TranslationHistoryWhereUniqueInput
  /**
   * In case the TranslationHistory found by the `where` argument doesn't exist, create a new TranslationHistory with this data.
   */
  create: Prisma.XOR<Prisma.TranslationHistoryCreateInput, Prisma.TranslationHistoryUncheckedCreateInput>
  /**
   * In case the TranslationHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TranslationHistoryUpdateInput, Prisma.TranslationHistoryUncheckedUpdateInput>
}

/**
 * TranslationHistory delete
 */
export type TranslationHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
  /**
   * Filter which TranslationHistory to delete.
   */
  where: Prisma.TranslationHistoryWhereUniqueInput
}

/**
 * TranslationHistory deleteMany
 */
export type TranslationHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationHistories to delete
   */
  where?: Prisma.TranslationHistoryWhereInput
  /**
   * Limit how many TranslationHistories to delete.
   */
  limit?: number
}

/**
 * TranslationHistory without action
 */
export type TranslationHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationHistory
   */
  select?: Prisma.TranslationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationHistory
   */
  omit?: Prisma.TranslationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationHistoryInclude<ExtArgs> | null
}
